// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Topo2A_AD_proj_dense_latency_ap_ufixed_15_0_4_0_0_ap_fixed_12_4_5_3_0_config8_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_rst
);


output   ap_ready;
input  [14:0] data_0_val;
input  [14:0] data_1_val;
input  [14:0] data_2_val;
input  [14:0] data_3_val;
input  [14:0] data_4_val;
input  [14:0] data_5_val;
input  [14:0] data_6_val;
input  [14:0] data_7_val;
input  [14:0] data_8_val;
input  [14:0] data_9_val;
input  [14:0] data_10_val;
input  [14:0] data_11_val;
input  [14:0] data_12_val;
input  [14:0] data_13_val;
input  [14:0] data_14_val;
input  [14:0] data_15_val;
output  [11:0] ap_return_0;
output  [11:0] ap_return_1;
output  [11:0] ap_return_2;
input   ap_rst;

wire   [14:0] mul_ln73_13_fu_235_p0;
wire   [18:0] zext_ln73_64_fu_3252_p1;
wire   [4:0] mul_ln73_13_fu_235_p1;
wire   [14:0] mul_ln73_9_fu_238_p0;
wire   [4:0] mul_ln73_9_fu_238_p1;
wire   [14:0] mul_ln73_16_fu_240_p0;
wire   [5:0] mul_ln73_16_fu_240_p1;
wire   [14:0] mul_ln73_11_fu_245_p0;
wire  signed [5:0] mul_ln73_11_fu_245_p1;
wire   [14:0] mul_ln73_17_fu_246_p0;
wire   [19:0] zext_ln73_155_fu_3468_p1;
wire  signed [4:0] mul_ln73_17_fu_246_p1;
wire   [14:0] mul_ln73_10_fu_247_p0;
wire  signed [5:0] mul_ln73_10_fu_247_p1;
wire   [14:0] mul_ln73_14_fu_248_p0;
wire  signed [4:0] mul_ln73_14_fu_248_p1;
wire   [14:0] mul_ln73_12_fu_257_p0;
wire  signed [4:0] mul_ln73_12_fu_257_p1;
wire   [14:0] mul_ln73_15_fu_269_p0;
wire  signed [4:0] mul_ln73_15_fu_269_p1;
wire   [14:0] mul_ln73_8_fu_270_p0;
wire  signed [4:0] mul_ln73_8_fu_270_p1;
wire   [14:0] mul_ln73_fu_279_p0;
wire  signed [4:0] mul_ln73_fu_279_p1;
wire   [14:0] mul_ln73_18_fu_280_p0;
wire   [4:0] mul_ln73_18_fu_280_p1;
wire   [15:0] zext_ln73_128_fu_2627_p1;
wire   [15:0] sub_ln73_fu_2631_p2;
wire   [4:0] trunc_ln_fu_2637_p4;
wire   [19:0] mul_ln73_fu_279_p2;
wire   [8:0] trunc_ln42_s_fu_2651_p4;
wire   [18:0] tmp_247_fu_2665_p3;
wire   [15:0] tmp_248_fu_2677_p3;
wire   [19:0] zext_ln73_238_fu_2685_p1;
wire   [19:0] zext_ln73_237_fu_2673_p1;
wire   [19:0] sub_ln73_195_fu_2689_p2;
wire   [8:0] trunc_ln42_137_fu_2695_p4;
wire   [18:0] tmp_249_fu_2709_p3;
wire   [15:0] tmp_250_fu_2721_p3;
wire   [19:0] zext_ln73_240_fu_2729_p1;
wire   [19:0] zext_ln73_239_fu_2717_p1;
wire   [19:0] sub_ln73_196_fu_2733_p2;
wire   [8:0] trunc_ln42_138_fu_2739_p4;
wire   [20:0] zext_ln73_241_fu_2753_p1;
wire   [20:0] sub_ln73_197_fu_2757_p2;
wire   [20:0] zext_ln73_242_fu_2763_p1;
wire   [20:0] sub_ln73_198_fu_2767_p2;
wire   [9:0] trunc_ln42_139_fu_2773_p4;
wire   [17:0] p_shl29_fu_2787_p3;
wire   [17:0] zext_ln73_243_fu_2795_p1;
wire   [16:0] tmp_251_fu_2814_p3;
wire   [18:0] zext_ln73_244_fu_2822_p1;
wire   [18:0] sub_ln73_200_fu_2826_p2;
wire   [18:0] zext_ln73_133_fu_2810_p1;
wire   [18:0] sub_ln73_201_fu_2832_p2;
wire   [7:0] trunc_ln42_140_fu_2838_p4;
wire   [17:0] p_shl30_fu_2856_p3;
wire   [17:0] zext_ln73_134_fu_2852_p1;
wire   [19:0] mul_ln73_8_fu_270_p2;
wire   [8:0] trunc_ln42_141_fu_2870_p4;
wire   [18:0] tmp_252_fu_2884_p3;
wire   [20:0] zext_ln73_245_fu_2892_p1;
wire   [15:0] tmp_253_fu_2902_p3;
wire   [20:0] sub_ln73_203_fu_2896_p2;
wire   [20:0] zext_ln73_246_fu_2910_p1;
wire   [20:0] sub_ln73_204_fu_2914_p2;
wire   [9:0] trunc_ln42_142_fu_2920_p4;
wire   [16:0] tmp_254_fu_2942_p3;
wire   [17:0] zext_ln73_247_fu_2950_p1;
wire   [17:0] zext_ln73_137_fu_2938_p1;
wire   [16:0] zext_ln73_136_fu_2934_p1;
wire   [15:0] zext_ln73_139_fu_2971_p1;
wire   [15:0] sub_ln73_25_fu_2975_p2;
wire   [4:0] trunc_ln42_143_fu_2981_p4;
wire   [15:0] tmp_255_fu_3003_p3;
wire   [17:0] p_shl31_fu_2995_p3;
wire   [17:0] zext_ln73_248_fu_3011_p1;
wire   [20:0] mul_ln73_10_fu_247_p2;
wire   [9:0] trunc_ln42_144_fu_3026_p4;
wire   [18:0] tmp_256_fu_3045_p3;
wire   [15:0] tmp_257_fu_3057_p3;
wire   [19:0] zext_ln73_249_fu_3053_p1;
wire   [19:0] zext_ln73_250_fu_3065_p1;
wire   [16:0] p_shl32_fu_3079_p3;
wire   [16:0] zext_ln73_143_fu_3075_p1;
wire   [20:0] mul_ln73_11_fu_245_p2;
wire   [9:0] trunc_ln42_145_fu_3093_p4;
wire   [19:0] mul_ln73_12_fu_257_p2;
wire   [8:0] trunc_ln42_146_fu_3116_p4;
wire   [15:0] tmp_258_fu_3138_p3;
wire   [19:0] p_shl33_fu_3130_p3;
wire   [19:0] zext_ln73_251_fu_3146_p1;
wire   [18:0] tmp_259_fu_3156_p3;
wire   [20:0] zext_ln73_252_fu_3164_p1;
wire   [20:0] sub_ln73_209_fu_3168_p2;
wire   [20:0] zext_ln73_144_fu_3107_p1;
wire   [20:0] sub_ln73_210_fu_3174_p2;
wire   [9:0] trunc_ln42_147_fu_3180_p4;
wire   [17:0] p_shl34_fu_3198_p3;
wire   [17:0] zext_ln73_146_fu_3194_p1;
wire   [16:0] tmp_260_fu_3212_p3;
wire   [17:0] zext_ln73_253_fu_3220_p1;
wire   [18:0] tmp_261_fu_3234_p3;
wire   [19:0] zext_ln73_254_fu_3242_p1;
wire   [19:0] zext_ln73_147_fu_3230_p1;
wire   [17:0] tmp_262_fu_3257_p3;
wire   [18:0] zext_ln73_255_fu_3265_p1;
wire   [16:0] tmp_263_fu_3275_p3;
wire   [17:0] zext_ln73_256_fu_3283_p1;
wire   [17:0] sub_ln73_212_fu_3287_p2;
wire   [6:0] trunc_ln42_148_fu_3293_p4;
wire   [15:0] tmp_264_fu_3312_p3;
wire   [16:0] zext_ln73_257_fu_3320_p1;
wire   [16:0] sub_ln73_213_fu_3324_p2;
wire   [5:0] trunc_ln42_149_fu_3330_p4;
wire   [19:0] mul_ln73_14_fu_248_p2;
wire   [8:0] trunc_ln42_150_fu_3344_p4;
wire   [16:0] p_shl35_fu_3362_p3;
wire   [16:0] zext_ln73_151_fu_3358_p1;
wire   [15:0] tmp_265_fu_3381_p3;
wire   [16:0] zext_ln73_258_fu_3389_p1;
wire   [16:0] sub_ln73_215_fu_3393_p2;
wire   [5:0] trunc_ln42_151_fu_3399_p4;
wire   [19:0] mul_ln73_15_fu_269_p2;
wire   [8:0] trunc_ln42_152_fu_3413_p4;
wire   [16:0] tmp_266_fu_3436_p3;
wire   [17:0] zext_ln73_153_fu_3427_p1;
wire   [17:0] zext_ln73_259_fu_3444_p1;
wire   [17:0] sub_ln73_216_fu_3448_p2;
wire   [6:0] trunc_ln42_153_fu_3454_p4;
wire   [19:0] mul_ln73_17_fu_246_p2;
wire   [8:0] trunc_ln42_154_fu_3473_p4;
wire   [18:0] p_shl36_fu_3491_p3;
wire   [18:0] zext_ln73_71_fu_3487_p1;
wire   [17:0] tmp_267_fu_3505_p3;
wire   [19:0] zext_ln73_260_fu_3513_p1;
wire   [19:0] sub_ln73_218_fu_3517_p2;
wire   [19:0] sub_ln73_219_fu_3523_p2;
wire   [8:0] trunc_ln42_155_fu_3529_p4;
wire   [15:0] tmp_268_fu_3556_p3;
wire   [17:0] p_shl37_fu_3548_p3;
wire   [17:0] zext_ln73_261_fu_3564_p1;
wire   [16:0] tmp_269_fu_3578_p3;
wire   [18:0] zext_ln73_262_fu_3586_p1;
wire   [18:0] sub_ln73_221_fu_3590_p2;
wire   [18:0] zext_ln73_158_fu_3574_p1;
wire   [18:0] tmp_270_fu_3602_p3;
wire   [15:0] tmp_271_fu_3614_p3;
wire   [19:0] zext_ln73_264_fu_3622_p1;
wire   [19:0] zext_ln73_263_fu_3610_p1;
wire   [18:0] mul_ln73_9_fu_238_p2;
wire   [7:0] tmp_fu_3632_p4;
wire   [19:0] add_ln73_23_fu_3069_p2;
wire   [17:0] sub_ln73_211_fu_3206_p2;
wire   [6:0] tmp_s_fu_3656_p4;
wire   [18:0] mul_ln73_13_fu_235_p2;
wire   [7:0] tmp_310_fu_3670_p4;
wire   [16:0] sub_ln73_214_fu_3370_p2;
wire   [5:0] tmp_311_fu_3684_p4;
wire   [19:0] mul_ln73_16_fu_240_p2;
wire   [8:0] tmp_312_fu_3698_p4;
wire   [17:0] sub_ln73_220_fu_3568_p2;
wire   [6:0] tmp_313_fu_3712_p4;
wire   [17:0] sub_ln73_202_fu_2864_p2;
wire   [6:0] tmp_314_fu_3726_p4;
wire   [17:0] add_ln73_fu_2954_p2;
wire   [6:0] tmp_315_fu_3740_p4;
wire   [3:0] tmp_316_fu_3754_p4;
wire   [16:0] sub_ln73_207_fu_3087_p2;
wire   [5:0] tmp_317_fu_3768_p4;
wire   [19:0] sub_ln73_208_fu_3150_p2;
wire   [8:0] tmp_318_fu_3782_p4;
wire   [17:0] add_ln73_24_fu_3224_p2;
wire   [6:0] tmp_319_fu_3796_p4;
wire   [18:0] add_ln73_26_fu_3269_p2;
wire   [5:0] tmp_320_fu_3820_p4;
wire   [18:0] sub_ln73_217_fu_3499_p2;
wire   [7:0] tmp_321_fu_3834_p4;
wire   [18:0] mul_ln73_18_fu_280_p2;
wire   [7:0] tmp_322_fu_3848_p4;
wire   [17:0] sub_ln73_199_fu_2799_p2;
wire   [6:0] tmp_323_fu_3862_p4;
wire   [16:0] sub_ln73_205_fu_2960_p2;
wire   [5:0] tmp_324_fu_3876_p4;
wire   [17:0] sub_ln73_206_fu_3015_p2;
wire   [4:0] tmp_325_fu_3900_p4;
wire   [19:0] add_ln73_25_fu_3246_p2;
wire   [8:0] tmp_326_fu_3914_p4;
wire   [3:0] tmp_327_fu_3928_p4;
wire   [18:0] sub_ln73_222_fu_3596_p2;
wire   [7:0] trunc_ln42_158_fu_3942_p4;
wire  signed [9:0] sext_ln73_fu_2647_p1;
wire  signed [9:0] sext_ln73_141_fu_2749_p1;
wire   [9:0] add_ln111_fu_3956_p2;
wire  signed [9:0] sext_ln73_143_fu_2848_p1;
wire   [9:0] zext_ln58_fu_3642_p1;
wire   [9:0] add_ln111_450_fu_3966_p2;
wire  signed [10:0] sext_ln111_296_fu_3972_p1;
wire  signed [10:0] sext_ln111_295_fu_3962_p1;
wire   [10:0] add_ln111_451_fu_3976_p2;
wire  signed [10:0] sext_ln73_144_fu_2930_p1;
wire  signed [10:0] sext_ln70_18_fu_3036_p1;
wire   [10:0] add_ln111_452_fu_3986_p2;
wire   [8:0] trunc_ln58_s_fu_3646_p4;
wire   [8:0] zext_ln58_129_fu_3666_p1;
wire   [8:0] add_ln111_453_fu_3996_p2;
wire   [11:0] zext_ln111_fu_4002_p1;
wire  signed [11:0] sext_ln111_298_fu_3992_p1;
wire   [11:0] add_ln111_454_fu_4006_p2;
wire  signed [11:0] sext_ln111_297_fu_3982_p1;
wire  signed [9:0] sext_ln73_146_fu_3126_p1;
wire   [9:0] zext_ln58_130_fu_3680_p1;
wire   [7:0] zext_ln58_131_fu_3694_p1;
wire  signed [7:0] sext_ln73_147_fu_3340_p1;
wire   [7:0] add_ln111_457_fu_4024_p2;
wire  signed [9:0] sext_ln111_299_fu_4030_p1;
wire   [9:0] add_ln111_456_fu_4018_p2;
wire   [9:0] add_ln111_458_fu_4034_p2;
wire   [10:0] zext_ln58_132_fu_3708_p1;
wire  signed [10:0] sext_ln73_149_fu_3483_p1;
wire  signed [8:0] sext_ln111_fu_3952_p1;
wire   [8:0] add_ln111_460_fu_4050_p2;
wire  signed [9:0] sext_ln111_301_fu_4056_p1;
wire   [9:0] zext_ln58_133_fu_3722_p1;
wire   [9:0] add_ln111_461_fu_4060_p2;
wire  signed [10:0] sext_ln111_302_fu_4066_p1;
wire   [10:0] add_ln111_459_fu_4044_p2;
wire   [10:0] add_ln111_462_fu_4070_p2;
wire  signed [11:0] sext_ln111_303_fu_4076_p1;
wire  signed [11:0] sext_ln111_300_fu_4040_p1;
wire   [11:0] add_ln111_463_fu_4080_p2;
wire   [11:0] add_ln111_455_fu_4012_p2;
wire   [19:0] sub_ln73_223_fu_3626_p2;
wire   [8:0] trunc_ln42_159_fu_4092_p4;
wire  signed [9:0] sext_ln73_140_fu_2661_p1;
wire   [9:0] zext_ln58_134_fu_3736_p1;
wire   [9:0] add_ln111_464_fu_4106_p2;
wire  signed [10:0] sext_ln73_142_fu_2783_p1;
wire   [10:0] zext_ln58_135_fu_3750_p1;
wire   [10:0] add_ln111_465_fu_4116_p2;
wire  signed [10:0] sext_ln111_305_fu_4112_p1;
wire   [10:0] add_ln111_466_fu_4122_p2;
wire   [5:0] zext_ln58_136_fu_3764_p1;
wire  signed [5:0] sext_ln73_145_fu_2991_p1;
wire   [5:0] add_ln111_467_fu_4132_p2;
wire   [9:0] zext_ln58_137_fu_3778_p1;
wire   [9:0] zext_ln58_138_fu_3792_p1;
wire   [9:0] add_ln111_468_fu_4142_p2;
wire   [10:0] zext_ln111_94_fu_4148_p1;
wire  signed [10:0] sext_ln111_307_fu_4138_p1;
wire   [10:0] add_ln111_469_fu_4152_p2;
wire  signed [11:0] sext_ln111_308_fu_4158_p1;
wire  signed [11:0] sext_ln111_306_fu_4128_p1;
wire   [7:0] zext_ln58_139_fu_3806_p1;
wire   [7:0] trunc_ln42_156_fu_3810_p4;
wire   [7:0] add_ln111_471_fu_4168_p2;
wire   [7:0] zext_ln58_140_fu_3830_p1;
wire  signed [7:0] sext_ln73_148_fu_3409_p1;
wire   [7:0] add_ln111_472_fu_4178_p2;
wire  signed [9:0] sext_ln111_309_fu_4184_p1;
wire   [9:0] zext_ln111_95_fu_4174_p1;
wire   [9:0] add_ln111_473_fu_4188_p2;
wire   [9:0] zext_ln58_141_fu_3844_p1;
wire  signed [9:0] sext_ln70_24_fu_3464_p1;
wire   [9:0] add_ln111_474_fu_4198_p2;
wire  signed [9:0] sext_ln111_304_fu_4102_p1;
wire   [9:0] add_ln111_475_fu_4208_p2;
wire  signed [10:0] sext_ln111_312_fu_4214_p1;
wire   [10:0] zext_ln58_142_fu_3858_p1;
wire   [10:0] add_ln111_476_fu_4218_p2;
wire  signed [10:0] sext_ln111_311_fu_4204_p1;
wire   [10:0] add_ln111_477_fu_4224_p2;
wire  signed [11:0] sext_ln111_313_fu_4230_p1;
wire  signed [11:0] sext_ln111_310_fu_4194_p1;
wire   [11:0] add_ln111_478_fu_4234_p2;
wire   [11:0] add_ln111_470_fu_4162_p2;
wire   [9:0] zext_ln58_143_fu_3872_p1;
wire  signed [9:0] sext_ln70_fu_2705_p1;
wire   [9:0] add_ln111_479_fu_4246_p2;
wire   [9:0] zext_ln42_fu_3886_p1;
wire  signed [9:0] sext_ln70_17_fu_2880_p1;
wire   [9:0] add_ln111_480_fu_4256_p2;
wire  signed [10:0] sext_ln111_315_fu_4262_p1;
wire  signed [10:0] sext_ln111_314_fu_4252_p1;
wire   [10:0] add_ln111_481_fu_4266_p2;
wire   [6:0] trunc_ln42_157_fu_3890_p4;
wire   [6:0] zext_ln58_144_fu_3910_p1;
wire   [6:0] add_ln111_482_fu_4276_p2;
wire  signed [10:0] sext_ln70_19_fu_3103_p1;
wire  signed [10:0] sext_ln70_20_fu_3190_p1;
wire   [10:0] add_ln111_483_fu_4286_p2;
wire  signed [11:0] sext_ln111_317_fu_4292_p1;
wire   [11:0] zext_ln111_83_fu_4282_p1;
wire   [11:0] add_ln111_484_fu_4296_p2;
wire  signed [11:0] sext_ln111_316_fu_4272_p1;
wire   [9:0] zext_ln58_145_fu_3924_p1;
wire  signed [9:0] sext_ln70_21_fu_3303_p1;
wire   [9:0] add_ln111_486_fu_4308_p2;
wire  signed [9:0] sext_ln70_22_fu_3354_p1;
wire  signed [9:0] sext_ln70_23_fu_3423_p1;
wire   [9:0] add_ln111_487_fu_4318_p2;
wire  signed [10:0] sext_ln111_319_fu_4324_p1;
wire  signed [10:0] sext_ln111_318_fu_4314_p1;
wire   [10:0] add_ln111_488_fu_4328_p2;
wire   [9:0] zext_ln42_72_fu_3938_p1;
wire  signed [9:0] sext_ln70_25_fu_3539_p1;
wire   [9:0] add_ln111_489_fu_4338_p2;
wire   [9:0] add_ln111_490_fu_4348_p2;
wire  signed [10:0] sext_ln111_322_fu_4354_p1;
wire  signed [10:0] sext_ln111_321_fu_4344_p1;
wire   [10:0] add_ln111_491_fu_4358_p2;
wire  signed [11:0] sext_ln111_323_fu_4364_p1;
wire  signed [11:0] sext_ln111_320_fu_4334_p1;
wire   [11:0] add_ln111_492_fu_4368_p2;
wire   [11:0] add_ln111_485_fu_4302_p2;
wire   [11:0] add_ln111_34_fu_4086_p2;
wire   [11:0] add_ln111_35_fu_4240_p2;
wire   [11:0] add_ln111_36_fu_4374_p2;
wire   [20:0] mul_ln73_10_fu_247_p00;
wire   [20:0] mul_ln73_11_fu_245_p00;
wire   [19:0] mul_ln73_12_fu_257_p00;
wire   [19:0] mul_ln73_14_fu_248_p00;
wire   [19:0] mul_ln73_15_fu_269_p00;
wire   [19:0] mul_ln73_16_fu_240_p00;
wire   [18:0] mul_ln73_18_fu_280_p00;
wire   [19:0] mul_ln73_8_fu_270_p00;
wire   [18:0] mul_ln73_9_fu_238_p00;
wire   [19:0] mul_ln73_fu_279_p00;

Topo2A_AD_proj_mul_15ns_5ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 19 ))
mul_15ns_5ns_19_1_1_U140(
    .din0(mul_ln73_13_fu_235_p0),
    .din1(mul_ln73_13_fu_235_p1),
    .dout(mul_ln73_13_fu_235_p2)
);

Topo2A_AD_proj_mul_15ns_5ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 19 ))
mul_15ns_5ns_19_1_1_U141(
    .din0(mul_ln73_9_fu_238_p0),
    .din1(mul_ln73_9_fu_238_p1),
    .dout(mul_ln73_9_fu_238_p2)
);

Topo2A_AD_proj_mul_15ns_6ns_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 20 ))
mul_15ns_6ns_20_1_1_U142(
    .din0(mul_ln73_16_fu_240_p0),
    .din1(mul_ln73_16_fu_240_p1),
    .dout(mul_ln73_16_fu_240_p2)
);

Topo2A_AD_proj_mul_15ns_6s_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 21 ))
mul_15ns_6s_21_1_1_U143(
    .din0(mul_ln73_11_fu_245_p0),
    .din1(mul_ln73_11_fu_245_p1),
    .dout(mul_ln73_11_fu_245_p2)
);

Topo2A_AD_proj_mul_15ns_5s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 20 ))
mul_15ns_5s_20_1_1_U144(
    .din0(mul_ln73_17_fu_246_p0),
    .din1(mul_ln73_17_fu_246_p1),
    .dout(mul_ln73_17_fu_246_p2)
);

Topo2A_AD_proj_mul_15ns_6s_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 21 ))
mul_15ns_6s_21_1_1_U145(
    .din0(mul_ln73_10_fu_247_p0),
    .din1(mul_ln73_10_fu_247_p1),
    .dout(mul_ln73_10_fu_247_p2)
);

Topo2A_AD_proj_mul_15ns_5s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 20 ))
mul_15ns_5s_20_1_1_U146(
    .din0(mul_ln73_14_fu_248_p0),
    .din1(mul_ln73_14_fu_248_p1),
    .dout(mul_ln73_14_fu_248_p2)
);

Topo2A_AD_proj_mul_15ns_5s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 20 ))
mul_15ns_5s_20_1_1_U147(
    .din0(mul_ln73_12_fu_257_p0),
    .din1(mul_ln73_12_fu_257_p1),
    .dout(mul_ln73_12_fu_257_p2)
);

Topo2A_AD_proj_mul_15ns_5s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 20 ))
mul_15ns_5s_20_1_1_U148(
    .din0(mul_ln73_15_fu_269_p0),
    .din1(mul_ln73_15_fu_269_p1),
    .dout(mul_ln73_15_fu_269_p2)
);

Topo2A_AD_proj_mul_15ns_5s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 20 ))
mul_15ns_5s_20_1_1_U149(
    .din0(mul_ln73_8_fu_270_p0),
    .din1(mul_ln73_8_fu_270_p1),
    .dout(mul_ln73_8_fu_270_p2)
);

Topo2A_AD_proj_mul_15ns_5s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 20 ))
mul_15ns_5s_20_1_1_U150(
    .din0(mul_ln73_fu_279_p0),
    .din1(mul_ln73_fu_279_p1),
    .dout(mul_ln73_fu_279_p2)
);

Topo2A_AD_proj_mul_15ns_5ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 19 ))
mul_15ns_5ns_19_1_1_U151(
    .din0(mul_ln73_18_fu_280_p0),
    .din1(mul_ln73_18_fu_280_p1),
    .dout(mul_ln73_18_fu_280_p2)
);

assign add_ln111_34_fu_4086_p2 = (add_ln111_463_fu_4080_p2 + add_ln111_455_fu_4012_p2);

assign add_ln111_35_fu_4240_p2 = (add_ln111_478_fu_4234_p2 + add_ln111_470_fu_4162_p2);

assign add_ln111_36_fu_4374_p2 = (add_ln111_492_fu_4368_p2 + add_ln111_485_fu_4302_p2);

assign add_ln111_450_fu_3966_p2 = ($signed(sext_ln73_143_fu_2848_p1) + $signed(zext_ln58_fu_3642_p1));

assign add_ln111_451_fu_3976_p2 = ($signed(sext_ln111_296_fu_3972_p1) + $signed(sext_ln111_295_fu_3962_p1));

assign add_ln111_452_fu_3986_p2 = ($signed(sext_ln73_144_fu_2930_p1) + $signed(sext_ln70_18_fu_3036_p1));

assign add_ln111_453_fu_3996_p2 = (trunc_ln58_s_fu_3646_p4 + zext_ln58_129_fu_3666_p1);

assign add_ln111_454_fu_4006_p2 = ($signed(zext_ln111_fu_4002_p1) + $signed(sext_ln111_298_fu_3992_p1));

assign add_ln111_455_fu_4012_p2 = ($signed(add_ln111_454_fu_4006_p2) + $signed(sext_ln111_297_fu_3982_p1));

assign add_ln111_456_fu_4018_p2 = ($signed(sext_ln73_146_fu_3126_p1) + $signed(zext_ln58_130_fu_3680_p1));

assign add_ln111_457_fu_4024_p2 = ($signed(zext_ln58_131_fu_3694_p1) + $signed(sext_ln73_147_fu_3340_p1));

assign add_ln111_458_fu_4034_p2 = ($signed(sext_ln111_299_fu_4030_p1) + $signed(add_ln111_456_fu_4018_p2));

assign add_ln111_459_fu_4044_p2 = ($signed(zext_ln58_132_fu_3708_p1) + $signed(sext_ln73_149_fu_3483_p1));

assign add_ln111_460_fu_4050_p2 = ($signed(sext_ln111_fu_3952_p1) + $signed(9'd48));

assign add_ln111_461_fu_4060_p2 = ($signed(sext_ln111_301_fu_4056_p1) + $signed(zext_ln58_133_fu_3722_p1));

assign add_ln111_462_fu_4070_p2 = ($signed(sext_ln111_302_fu_4066_p1) + $signed(add_ln111_459_fu_4044_p2));

assign add_ln111_463_fu_4080_p2 = ($signed(sext_ln111_303_fu_4076_p1) + $signed(sext_ln111_300_fu_4040_p1));

assign add_ln111_464_fu_4106_p2 = ($signed(sext_ln73_140_fu_2661_p1) + $signed(zext_ln58_134_fu_3736_p1));

assign add_ln111_465_fu_4116_p2 = ($signed(sext_ln73_142_fu_2783_p1) + $signed(zext_ln58_135_fu_3750_p1));

assign add_ln111_466_fu_4122_p2 = ($signed(add_ln111_465_fu_4116_p2) + $signed(sext_ln111_305_fu_4112_p1));

assign add_ln111_467_fu_4132_p2 = ($signed(zext_ln58_136_fu_3764_p1) + $signed(sext_ln73_145_fu_2991_p1));

assign add_ln111_468_fu_4142_p2 = (zext_ln58_137_fu_3778_p1 + zext_ln58_138_fu_3792_p1);

assign add_ln111_469_fu_4152_p2 = ($signed(zext_ln111_94_fu_4148_p1) + $signed(sext_ln111_307_fu_4138_p1));

assign add_ln111_470_fu_4162_p2 = ($signed(sext_ln111_308_fu_4158_p1) + $signed(sext_ln111_306_fu_4128_p1));

assign add_ln111_471_fu_4168_p2 = (zext_ln58_139_fu_3806_p1 + trunc_ln42_156_fu_3810_p4);

assign add_ln111_472_fu_4178_p2 = ($signed(zext_ln58_140_fu_3830_p1) + $signed(sext_ln73_148_fu_3409_p1));

assign add_ln111_473_fu_4188_p2 = ($signed(sext_ln111_309_fu_4184_p1) + $signed(zext_ln111_95_fu_4174_p1));

assign add_ln111_474_fu_4198_p2 = ($signed(zext_ln58_141_fu_3844_p1) + $signed(sext_ln70_24_fu_3464_p1));

assign add_ln111_475_fu_4208_p2 = ($signed(sext_ln111_304_fu_4102_p1) + $signed(10'd80));

assign add_ln111_476_fu_4218_p2 = ($signed(sext_ln111_312_fu_4214_p1) + $signed(zext_ln58_142_fu_3858_p1));

assign add_ln111_477_fu_4224_p2 = ($signed(add_ln111_476_fu_4218_p2) + $signed(sext_ln111_311_fu_4204_p1));

assign add_ln111_478_fu_4234_p2 = ($signed(sext_ln111_313_fu_4230_p1) + $signed(sext_ln111_310_fu_4194_p1));

assign add_ln111_479_fu_4246_p2 = ($signed(zext_ln58_143_fu_3872_p1) + $signed(sext_ln70_fu_2705_p1));

assign add_ln111_480_fu_4256_p2 = ($signed(zext_ln42_fu_3886_p1) + $signed(sext_ln70_17_fu_2880_p1));

assign add_ln111_481_fu_4266_p2 = ($signed(sext_ln111_315_fu_4262_p1) + $signed(sext_ln111_314_fu_4252_p1));

assign add_ln111_482_fu_4276_p2 = (trunc_ln42_157_fu_3890_p4 + zext_ln58_144_fu_3910_p1);

assign add_ln111_483_fu_4286_p2 = ($signed(sext_ln70_19_fu_3103_p1) + $signed(sext_ln70_20_fu_3190_p1));

assign add_ln111_484_fu_4296_p2 = ($signed(sext_ln111_317_fu_4292_p1) + $signed(zext_ln111_83_fu_4282_p1));

assign add_ln111_485_fu_4302_p2 = ($signed(add_ln111_484_fu_4296_p2) + $signed(sext_ln111_316_fu_4272_p1));

assign add_ln111_486_fu_4308_p2 = ($signed(zext_ln58_145_fu_3924_p1) + $signed(sext_ln70_21_fu_3303_p1));

assign add_ln111_487_fu_4318_p2 = ($signed(sext_ln70_22_fu_3354_p1) + $signed(sext_ln70_23_fu_3423_p1));

assign add_ln111_488_fu_4328_p2 = ($signed(sext_ln111_319_fu_4324_p1) + $signed(sext_ln111_318_fu_4314_p1));

assign add_ln111_489_fu_4338_p2 = ($signed(zext_ln42_72_fu_3938_p1) + $signed(sext_ln70_25_fu_3539_p1));

assign add_ln111_490_fu_4348_p2 = ($signed(sext_ln111_304_fu_4102_p1) + $signed(10'd960));

assign add_ln111_491_fu_4358_p2 = ($signed(sext_ln111_322_fu_4354_p1) + $signed(sext_ln111_321_fu_4344_p1));

assign add_ln111_492_fu_4368_p2 = ($signed(sext_ln111_323_fu_4364_p1) + $signed(sext_ln111_320_fu_4334_p1));

assign add_ln111_fu_3956_p2 = ($signed(sext_ln73_fu_2647_p1) + $signed(sext_ln73_141_fu_2749_p1));

assign add_ln73_23_fu_3069_p2 = (zext_ln73_249_fu_3053_p1 + zext_ln73_250_fu_3065_p1);

assign add_ln73_24_fu_3224_p2 = (zext_ln73_253_fu_3220_p1 + zext_ln73_146_fu_3194_p1);

assign add_ln73_25_fu_3246_p2 = (zext_ln73_254_fu_3242_p1 + zext_ln73_147_fu_3230_p1);

assign add_ln73_26_fu_3269_p2 = (zext_ln73_255_fu_3265_p1 + zext_ln73_64_fu_3252_p1);

assign add_ln73_fu_2954_p2 = (zext_ln73_247_fu_2950_p1 + zext_ln73_137_fu_2938_p1);

assign ap_ready = 1'b1;

assign mul_ln73_10_fu_247_p00 = data_5_val;

assign mul_ln73_11_fu_245_p00 = data_6_val;

assign mul_ln73_12_fu_257_p00 = data_7_val;

assign mul_ln73_14_fu_248_p00 = data_10_val;

assign mul_ln73_15_fu_269_p00 = data_11_val;

assign mul_ln73_16_fu_240_p00 = data_12_val;

assign mul_ln73_18_fu_280_p00 = data_14_val;

assign mul_ln73_8_fu_270_p00 = data_2_val;

assign mul_ln73_9_fu_238_p00 = data_4_val;

assign mul_ln73_fu_279_p00 = data_0_val;

assign p_shl29_fu_2787_p3 = {{data_1_val}, {3'd0}};

assign p_shl30_fu_2856_p3 = {{data_2_val}, {3'd0}};

assign p_shl31_fu_2995_p3 = {{data_4_val}, {3'd0}};

assign p_shl32_fu_3079_p3 = {{data_6_val}, {2'd0}};

assign p_shl33_fu_3130_p3 = {{data_7_val}, {5'd0}};

assign p_shl34_fu_3198_p3 = {{data_8_val}, {3'd0}};

assign p_shl35_fu_3362_p3 = {{data_11_val}, {2'd0}};

assign p_shl36_fu_3491_p3 = {{data_13_val}, {4'd0}};

assign p_shl37_fu_3548_p3 = {{data_14_val}, {3'd0}};

assign sext_ln111_295_fu_3962_p1 = $signed(add_ln111_fu_3956_p2);

assign sext_ln111_296_fu_3972_p1 = $signed(add_ln111_450_fu_3966_p2);

assign sext_ln111_297_fu_3982_p1 = $signed(add_ln111_451_fu_3976_p2);

assign sext_ln111_298_fu_3992_p1 = $signed(add_ln111_452_fu_3986_p2);

assign sext_ln111_299_fu_4030_p1 = $signed(add_ln111_457_fu_4024_p2);

assign sext_ln111_300_fu_4040_p1 = $signed(add_ln111_458_fu_4034_p2);

assign sext_ln111_301_fu_4056_p1 = $signed(add_ln111_460_fu_4050_p2);

assign sext_ln111_302_fu_4066_p1 = $signed(add_ln111_461_fu_4060_p2);

assign sext_ln111_303_fu_4076_p1 = $signed(add_ln111_462_fu_4070_p2);

assign sext_ln111_304_fu_4102_p1 = $signed(trunc_ln42_159_fu_4092_p4);

assign sext_ln111_305_fu_4112_p1 = $signed(add_ln111_464_fu_4106_p2);

assign sext_ln111_306_fu_4128_p1 = $signed(add_ln111_466_fu_4122_p2);

assign sext_ln111_307_fu_4138_p1 = $signed(add_ln111_467_fu_4132_p2);

assign sext_ln111_308_fu_4158_p1 = $signed(add_ln111_469_fu_4152_p2);

assign sext_ln111_309_fu_4184_p1 = $signed(add_ln111_472_fu_4178_p2);

assign sext_ln111_310_fu_4194_p1 = $signed(add_ln111_473_fu_4188_p2);

assign sext_ln111_311_fu_4204_p1 = $signed(add_ln111_474_fu_4198_p2);

assign sext_ln111_312_fu_4214_p1 = $signed(add_ln111_475_fu_4208_p2);

assign sext_ln111_313_fu_4230_p1 = $signed(add_ln111_477_fu_4224_p2);

assign sext_ln111_314_fu_4252_p1 = $signed(add_ln111_479_fu_4246_p2);

assign sext_ln111_315_fu_4262_p1 = $signed(add_ln111_480_fu_4256_p2);

assign sext_ln111_316_fu_4272_p1 = $signed(add_ln111_481_fu_4266_p2);

assign sext_ln111_317_fu_4292_p1 = $signed(add_ln111_483_fu_4286_p2);

assign sext_ln111_318_fu_4314_p1 = $signed(add_ln111_486_fu_4308_p2);

assign sext_ln111_319_fu_4324_p1 = $signed(add_ln111_487_fu_4318_p2);

assign sext_ln111_320_fu_4334_p1 = $signed(add_ln111_488_fu_4328_p2);

assign sext_ln111_321_fu_4344_p1 = $signed(add_ln111_489_fu_4338_p2);

assign sext_ln111_322_fu_4354_p1 = $signed(add_ln111_490_fu_4348_p2);

assign sext_ln111_323_fu_4364_p1 = $signed(add_ln111_491_fu_4358_p2);

assign sext_ln111_fu_3952_p1 = $signed(trunc_ln42_158_fu_3942_p4);

assign sext_ln70_17_fu_2880_p1 = $signed(trunc_ln42_141_fu_2870_p4);

assign sext_ln70_18_fu_3036_p1 = $signed(trunc_ln42_144_fu_3026_p4);

assign sext_ln70_19_fu_3103_p1 = $signed(trunc_ln42_145_fu_3093_p4);

assign sext_ln70_20_fu_3190_p1 = $signed(trunc_ln42_147_fu_3180_p4);

assign sext_ln70_21_fu_3303_p1 = $signed(trunc_ln42_148_fu_3293_p4);

assign sext_ln70_22_fu_3354_p1 = $signed(trunc_ln42_150_fu_3344_p4);

assign sext_ln70_23_fu_3423_p1 = $signed(trunc_ln42_152_fu_3413_p4);

assign sext_ln70_24_fu_3464_p1 = $signed(trunc_ln42_153_fu_3454_p4);

assign sext_ln70_25_fu_3539_p1 = $signed(trunc_ln42_155_fu_3529_p4);

assign sext_ln70_fu_2705_p1 = $signed(trunc_ln42_137_fu_2695_p4);

assign sext_ln73_140_fu_2661_p1 = $signed(trunc_ln42_s_fu_2651_p4);

assign sext_ln73_141_fu_2749_p1 = $signed(trunc_ln42_138_fu_2739_p4);

assign sext_ln73_142_fu_2783_p1 = $signed(trunc_ln42_139_fu_2773_p4);

assign sext_ln73_143_fu_2848_p1 = $signed(trunc_ln42_140_fu_2838_p4);

assign sext_ln73_144_fu_2930_p1 = $signed(trunc_ln42_142_fu_2920_p4);

assign sext_ln73_145_fu_2991_p1 = $signed(trunc_ln42_143_fu_2981_p4);

assign sext_ln73_146_fu_3126_p1 = $signed(trunc_ln42_146_fu_3116_p4);

assign sext_ln73_147_fu_3340_p1 = $signed(trunc_ln42_149_fu_3330_p4);

assign sext_ln73_148_fu_3409_p1 = $signed(trunc_ln42_151_fu_3399_p4);

assign sext_ln73_149_fu_3483_p1 = $signed(trunc_ln42_154_fu_3473_p4);

assign sext_ln73_fu_2647_p1 = $signed(trunc_ln_fu_2637_p4);

assign sub_ln73_195_fu_2689_p2 = (zext_ln73_238_fu_2685_p1 - zext_ln73_237_fu_2673_p1);

assign sub_ln73_196_fu_2733_p2 = (zext_ln73_240_fu_2729_p1 - zext_ln73_239_fu_2717_p1);

assign sub_ln73_197_fu_2757_p2 = (21'd0 - zext_ln73_241_fu_2753_p1);

assign sub_ln73_198_fu_2767_p2 = (sub_ln73_197_fu_2757_p2 - zext_ln73_242_fu_2763_p1);

assign sub_ln73_199_fu_2799_p2 = (p_shl29_fu_2787_p3 - zext_ln73_243_fu_2795_p1);

assign sub_ln73_200_fu_2826_p2 = (19'd0 - zext_ln73_244_fu_2822_p1);

assign sub_ln73_201_fu_2832_p2 = (sub_ln73_200_fu_2826_p2 - zext_ln73_133_fu_2810_p1);

assign sub_ln73_202_fu_2864_p2 = (p_shl30_fu_2856_p3 - zext_ln73_134_fu_2852_p1);

assign sub_ln73_203_fu_2896_p2 = (21'd0 - zext_ln73_245_fu_2892_p1);

assign sub_ln73_204_fu_2914_p2 = (sub_ln73_203_fu_2896_p2 - zext_ln73_246_fu_2910_p1);

assign sub_ln73_205_fu_2960_p2 = (tmp_254_fu_2942_p3 - zext_ln73_136_fu_2934_p1);

assign sub_ln73_206_fu_3015_p2 = (p_shl31_fu_2995_p3 - zext_ln73_248_fu_3011_p1);

assign sub_ln73_207_fu_3087_p2 = (p_shl32_fu_3079_p3 - zext_ln73_143_fu_3075_p1);

assign sub_ln73_208_fu_3150_p2 = (p_shl33_fu_3130_p3 - zext_ln73_251_fu_3146_p1);

assign sub_ln73_209_fu_3168_p2 = (21'd0 - zext_ln73_252_fu_3164_p1);

assign sub_ln73_210_fu_3174_p2 = (sub_ln73_209_fu_3168_p2 - zext_ln73_144_fu_3107_p1);

assign sub_ln73_211_fu_3206_p2 = (p_shl34_fu_3198_p3 - zext_ln73_146_fu_3194_p1);

assign sub_ln73_212_fu_3287_p2 = (18'd0 - zext_ln73_256_fu_3283_p1);

assign sub_ln73_213_fu_3324_p2 = (17'd0 - zext_ln73_257_fu_3320_p1);

assign sub_ln73_214_fu_3370_p2 = (p_shl35_fu_3362_p3 - zext_ln73_151_fu_3358_p1);

assign sub_ln73_215_fu_3393_p2 = (17'd0 - zext_ln73_258_fu_3389_p1);

assign sub_ln73_216_fu_3448_p2 = (zext_ln73_153_fu_3427_p1 - zext_ln73_259_fu_3444_p1);

assign sub_ln73_217_fu_3499_p2 = (p_shl36_fu_3491_p3 - zext_ln73_71_fu_3487_p1);

assign sub_ln73_218_fu_3517_p2 = (20'd0 - zext_ln73_260_fu_3513_p1);

assign sub_ln73_219_fu_3523_p2 = (sub_ln73_218_fu_3517_p2 - zext_ln73_155_fu_3468_p1);

assign sub_ln73_220_fu_3568_p2 = (p_shl37_fu_3548_p3 - zext_ln73_261_fu_3564_p1);

assign sub_ln73_221_fu_3590_p2 = (19'd0 - zext_ln73_262_fu_3586_p1);

assign sub_ln73_222_fu_3596_p2 = (sub_ln73_221_fu_3590_p2 - zext_ln73_158_fu_3574_p1);

assign sub_ln73_223_fu_3626_p2 = (zext_ln73_264_fu_3622_p1 - zext_ln73_263_fu_3610_p1);

assign sub_ln73_25_fu_2975_p2 = (16'd0 - zext_ln73_139_fu_2971_p1);

assign sub_ln73_fu_2631_p2 = (16'd0 - zext_ln73_128_fu_2627_p1);

assign tmp_247_fu_2665_p3 = {{data_0_val}, {4'd0}};

assign tmp_248_fu_2677_p3 = {{data_0_val}, {1'd0}};

assign tmp_249_fu_2709_p3 = {{data_1_val}, {4'd0}};

assign tmp_250_fu_2721_p3 = {{data_1_val}, {1'd0}};

assign tmp_251_fu_2814_p3 = {{data_2_val}, {2'd0}};

assign tmp_252_fu_2884_p3 = {{data_3_val}, {4'd0}};

assign tmp_253_fu_2902_p3 = {{data_3_val}, {1'd0}};

assign tmp_254_fu_2942_p3 = {{data_3_val}, {2'd0}};

assign tmp_255_fu_3003_p3 = {{data_4_val}, {1'd0}};

assign tmp_256_fu_3045_p3 = {{data_6_val}, {4'd0}};

assign tmp_257_fu_3057_p3 = {{data_6_val}, {1'd0}};

assign tmp_258_fu_3138_p3 = {{data_7_val}, {1'd0}};

assign tmp_259_fu_3156_p3 = {{data_7_val}, {4'd0}};

assign tmp_260_fu_3212_p3 = {{data_8_val}, {2'd0}};

assign tmp_261_fu_3234_p3 = {{data_8_val}, {4'd0}};

assign tmp_262_fu_3257_p3 = {{data_9_val}, {3'd0}};

assign tmp_263_fu_3275_p3 = {{data_9_val}, {2'd0}};

assign tmp_264_fu_3312_p3 = {{data_10_val}, {1'd0}};

assign tmp_265_fu_3381_p3 = {{data_11_val}, {1'd0}};

assign tmp_266_fu_3436_p3 = {{data_12_val}, {2'd0}};

assign tmp_267_fu_3505_p3 = {{data_13_val}, {3'd0}};

assign tmp_268_fu_3556_p3 = {{data_14_val}, {1'd0}};

assign tmp_269_fu_3578_p3 = {{data_15_val}, {2'd0}};

assign tmp_270_fu_3602_p3 = {{data_15_val}, {4'd0}};

assign tmp_271_fu_3614_p3 = {{data_15_val}, {1'd0}};

assign tmp_310_fu_3670_p4 = {{mul_ln73_13_fu_235_p2[18:11]}};

assign tmp_311_fu_3684_p4 = {{sub_ln73_214_fu_3370_p2[16:11]}};

assign tmp_312_fu_3698_p4 = {{mul_ln73_16_fu_240_p2[19:11]}};

assign tmp_313_fu_3712_p4 = {{sub_ln73_220_fu_3568_p2[17:11]}};

assign tmp_314_fu_3726_p4 = {{sub_ln73_202_fu_2864_p2[17:11]}};

assign tmp_315_fu_3740_p4 = {{add_ln73_fu_2954_p2[17:11]}};

assign tmp_316_fu_3754_p4 = {{data_5_val[14:11]}};

assign tmp_317_fu_3768_p4 = {{sub_ln73_207_fu_3087_p2[16:11]}};

assign tmp_318_fu_3782_p4 = {{sub_ln73_208_fu_3150_p2[19:11]}};

assign tmp_319_fu_3796_p4 = {{add_ln73_24_fu_3224_p2[17:11]}};

assign tmp_320_fu_3820_p4 = {{data_10_val[14:9]}};

assign tmp_321_fu_3834_p4 = {{sub_ln73_217_fu_3499_p2[18:11]}};

assign tmp_322_fu_3848_p4 = {{mul_ln73_18_fu_280_p2[18:11]}};

assign tmp_323_fu_3862_p4 = {{sub_ln73_199_fu_2799_p2[17:11]}};

assign tmp_324_fu_3876_p4 = {{sub_ln73_205_fu_2960_p2[16:11]}};

assign tmp_325_fu_3900_p4 = {{data_5_val[14:10]}};

assign tmp_326_fu_3914_p4 = {{add_ln73_25_fu_3246_p2[19:11]}};

assign tmp_327_fu_3928_p4 = {{data_14_val[14:11]}};

assign tmp_fu_3632_p4 = {{mul_ln73_9_fu_238_p2[18:11]}};

assign tmp_s_fu_3656_p4 = {{sub_ln73_211_fu_3206_p2[17:11]}};

assign trunc_ln42_137_fu_2695_p4 = {{sub_ln73_195_fu_2689_p2[19:11]}};

assign trunc_ln42_138_fu_2739_p4 = {{sub_ln73_196_fu_2733_p2[19:11]}};

assign trunc_ln42_139_fu_2773_p4 = {{sub_ln73_198_fu_2767_p2[20:11]}};

assign trunc_ln42_140_fu_2838_p4 = {{sub_ln73_201_fu_2832_p2[18:11]}};

assign trunc_ln42_141_fu_2870_p4 = {{mul_ln73_8_fu_270_p2[19:11]}};

assign trunc_ln42_142_fu_2920_p4 = {{sub_ln73_204_fu_2914_p2[20:11]}};

assign trunc_ln42_143_fu_2981_p4 = {{sub_ln73_25_fu_2975_p2[15:11]}};

assign trunc_ln42_144_fu_3026_p4 = {{mul_ln73_10_fu_247_p2[20:11]}};

assign trunc_ln42_145_fu_3093_p4 = {{mul_ln73_11_fu_245_p2[20:11]}};

assign trunc_ln42_146_fu_3116_p4 = {{mul_ln73_12_fu_257_p2[19:11]}};

assign trunc_ln42_147_fu_3180_p4 = {{sub_ln73_210_fu_3174_p2[20:11]}};

assign trunc_ln42_148_fu_3293_p4 = {{sub_ln73_212_fu_3287_p2[17:11]}};

assign trunc_ln42_149_fu_3330_p4 = {{sub_ln73_213_fu_3324_p2[16:11]}};

assign trunc_ln42_150_fu_3344_p4 = {{mul_ln73_14_fu_248_p2[19:11]}};

assign trunc_ln42_151_fu_3399_p4 = {{sub_ln73_215_fu_3393_p2[16:11]}};

assign trunc_ln42_152_fu_3413_p4 = {{mul_ln73_15_fu_269_p2[19:11]}};

assign trunc_ln42_153_fu_3454_p4 = {{sub_ln73_216_fu_3448_p2[17:11]}};

assign trunc_ln42_154_fu_3473_p4 = {{mul_ln73_17_fu_246_p2[19:11]}};

assign trunc_ln42_155_fu_3529_p4 = {{sub_ln73_219_fu_3523_p2[19:11]}};

assign trunc_ln42_156_fu_3810_p4 = {{add_ln73_26_fu_3269_p2[18:11]}};

assign trunc_ln42_157_fu_3890_p4 = {{sub_ln73_206_fu_3015_p2[17:11]}};

assign trunc_ln42_158_fu_3942_p4 = {{sub_ln73_222_fu_3596_p2[18:11]}};

assign trunc_ln42_159_fu_4092_p4 = {{sub_ln73_223_fu_3626_p2[19:11]}};

assign trunc_ln42_s_fu_2651_p4 = {{mul_ln73_fu_279_p2[19:11]}};

assign trunc_ln58_s_fu_3646_p4 = {{add_ln73_23_fu_3069_p2[19:11]}};

assign trunc_ln_fu_2637_p4 = {{sub_ln73_fu_2631_p2[15:11]}};

assign zext_ln111_83_fu_4282_p1 = add_ln111_482_fu_4276_p2;

assign zext_ln111_94_fu_4148_p1 = add_ln111_468_fu_4142_p2;

assign zext_ln111_95_fu_4174_p1 = add_ln111_471_fu_4168_p2;

assign zext_ln111_fu_4002_p1 = add_ln111_453_fu_3996_p2;

assign zext_ln42_72_fu_3938_p1 = tmp_327_fu_3928_p4;

assign zext_ln42_fu_3886_p1 = tmp_324_fu_3876_p4;

assign zext_ln58_129_fu_3666_p1 = tmp_s_fu_3656_p4;

assign zext_ln58_130_fu_3680_p1 = tmp_310_fu_3670_p4;

assign zext_ln58_131_fu_3694_p1 = tmp_311_fu_3684_p4;

assign zext_ln58_132_fu_3708_p1 = tmp_312_fu_3698_p4;

assign zext_ln58_133_fu_3722_p1 = tmp_313_fu_3712_p4;

assign zext_ln58_134_fu_3736_p1 = tmp_314_fu_3726_p4;

assign zext_ln58_135_fu_3750_p1 = tmp_315_fu_3740_p4;

assign zext_ln58_136_fu_3764_p1 = tmp_316_fu_3754_p4;

assign zext_ln58_137_fu_3778_p1 = tmp_317_fu_3768_p4;

assign zext_ln58_138_fu_3792_p1 = tmp_318_fu_3782_p4;

assign zext_ln58_139_fu_3806_p1 = tmp_319_fu_3796_p4;

assign zext_ln58_140_fu_3830_p1 = tmp_320_fu_3820_p4;

assign zext_ln58_141_fu_3844_p1 = tmp_321_fu_3834_p4;

assign zext_ln58_142_fu_3858_p1 = tmp_322_fu_3848_p4;

assign zext_ln58_143_fu_3872_p1 = tmp_323_fu_3862_p4;

assign zext_ln58_144_fu_3910_p1 = tmp_325_fu_3900_p4;

assign zext_ln58_145_fu_3924_p1 = tmp_326_fu_3914_p4;

assign zext_ln58_fu_3642_p1 = tmp_fu_3632_p4;

assign zext_ln73_128_fu_2627_p1 = data_0_val;

assign zext_ln73_133_fu_2810_p1 = data_2_val;

assign zext_ln73_134_fu_2852_p1 = data_2_val;

assign zext_ln73_136_fu_2934_p1 = data_3_val;

assign zext_ln73_137_fu_2938_p1 = data_3_val;

assign zext_ln73_139_fu_2971_p1 = data_4_val;

assign zext_ln73_143_fu_3075_p1 = data_6_val;

assign zext_ln73_144_fu_3107_p1 = data_7_val;

assign zext_ln73_146_fu_3194_p1 = data_8_val;

assign zext_ln73_147_fu_3230_p1 = data_8_val;

assign zext_ln73_151_fu_3358_p1 = data_11_val;

assign zext_ln73_153_fu_3427_p1 = data_12_val;

assign zext_ln73_155_fu_3468_p1 = data_13_val;

assign zext_ln73_158_fu_3574_p1 = data_15_val;

assign zext_ln73_237_fu_2673_p1 = tmp_247_fu_2665_p3;

assign zext_ln73_238_fu_2685_p1 = tmp_248_fu_2677_p3;

assign zext_ln73_239_fu_2717_p1 = tmp_249_fu_2709_p3;

assign zext_ln73_240_fu_2729_p1 = tmp_250_fu_2721_p3;

assign zext_ln73_241_fu_2753_p1 = tmp_249_fu_2709_p3;

assign zext_ln73_242_fu_2763_p1 = tmp_250_fu_2721_p3;

assign zext_ln73_243_fu_2795_p1 = tmp_250_fu_2721_p3;

assign zext_ln73_244_fu_2822_p1 = tmp_251_fu_2814_p3;

assign zext_ln73_245_fu_2892_p1 = tmp_252_fu_2884_p3;

assign zext_ln73_246_fu_2910_p1 = tmp_253_fu_2902_p3;

assign zext_ln73_247_fu_2950_p1 = tmp_254_fu_2942_p3;

assign zext_ln73_248_fu_3011_p1 = tmp_255_fu_3003_p3;

assign zext_ln73_249_fu_3053_p1 = tmp_256_fu_3045_p3;

assign zext_ln73_250_fu_3065_p1 = tmp_257_fu_3057_p3;

assign zext_ln73_251_fu_3146_p1 = tmp_258_fu_3138_p3;

assign zext_ln73_252_fu_3164_p1 = tmp_259_fu_3156_p3;

assign zext_ln73_253_fu_3220_p1 = tmp_260_fu_3212_p3;

assign zext_ln73_254_fu_3242_p1 = tmp_261_fu_3234_p3;

assign zext_ln73_255_fu_3265_p1 = tmp_262_fu_3257_p3;

assign zext_ln73_256_fu_3283_p1 = tmp_263_fu_3275_p3;

assign zext_ln73_257_fu_3320_p1 = tmp_264_fu_3312_p3;

assign zext_ln73_258_fu_3389_p1 = tmp_265_fu_3381_p3;

assign zext_ln73_259_fu_3444_p1 = tmp_266_fu_3436_p3;

assign zext_ln73_260_fu_3513_p1 = tmp_267_fu_3505_p3;

assign zext_ln73_261_fu_3564_p1 = tmp_268_fu_3556_p3;

assign zext_ln73_262_fu_3586_p1 = tmp_269_fu_3578_p3;

assign zext_ln73_263_fu_3610_p1 = tmp_270_fu_3602_p3;

assign zext_ln73_264_fu_3622_p1 = tmp_271_fu_3614_p3;

assign zext_ln73_64_fu_3252_p1 = data_9_val;

assign zext_ln73_71_fu_3487_p1 = data_13_val;

assign ap_return_0 = add_ln111_34_fu_4086_p2;

assign ap_return_1 = add_ln111_35_fu_4240_p2;

assign ap_return_2 = add_ln111_36_fu_4374_p2;

assign mul_ln73_10_fu_247_p0 = mul_ln73_10_fu_247_p00;

assign mul_ln73_10_fu_247_p1 = 21'd2097133;

assign mul_ln73_11_fu_245_p0 = mul_ln73_11_fu_245_p00;

assign mul_ln73_11_fu_245_p1 = 21'd2097133;

assign mul_ln73_12_fu_257_p0 = mul_ln73_12_fu_257_p00;

assign mul_ln73_12_fu_257_p1 = 20'd1048563;

assign mul_ln73_13_fu_235_p0 = zext_ln73_64_fu_3252_p1;

assign mul_ln73_13_fu_235_p1 = 19'd11;

assign mul_ln73_14_fu_248_p0 = mul_ln73_14_fu_248_p00;

assign mul_ln73_14_fu_248_p1 = 20'd1048563;

assign mul_ln73_15_fu_269_p0 = mul_ln73_15_fu_269_p00;

assign mul_ln73_15_fu_269_p1 = 20'd1048563;

assign mul_ln73_16_fu_240_p0 = mul_ln73_16_fu_240_p00;

assign mul_ln73_16_fu_240_p1 = 20'd19;

assign mul_ln73_17_fu_246_p0 = zext_ln73_155_fu_3468_p1;

assign mul_ln73_17_fu_246_p1 = 20'd1048565;

assign mul_ln73_18_fu_280_p0 = mul_ln73_18_fu_280_p00;

assign mul_ln73_18_fu_280_p1 = 19'd13;

assign mul_ln73_8_fu_270_p0 = mul_ln73_8_fu_270_p00;

assign mul_ln73_8_fu_270_p1 = 20'd1048563;

assign mul_ln73_9_fu_238_p0 = mul_ln73_9_fu_238_p00;

assign mul_ln73_9_fu_238_p1 = 19'd11;

assign mul_ln73_fu_279_p0 = mul_ln73_fu_279_p00;

assign mul_ln73_fu_279_p1 = 20'd1048563;

endmodule //Topo2A_AD_proj_dense_latency_ap_ufixed_15_0_4_0_0_ap_fixed_12_4_5_3_0_config8_s
