// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Topo2A_AD_proj_relu_ap_fixed_19_11_5_3_0_ap_ufixed_15_0_4_0_0_relu_config7_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_rst
);


output   ap_ready;
input  [18:0] data_0_val;
input  [18:0] data_1_val;
input  [18:0] data_2_val;
input  [18:0] data_3_val;
input  [18:0] data_4_val;
input  [18:0] data_5_val;
input  [18:0] data_6_val;
input  [18:0] data_7_val;
input  [18:0] data_8_val;
input  [18:0] data_9_val;
input  [18:0] data_10_val;
input  [18:0] data_11_val;
input  [18:0] data_12_val;
input  [18:0] data_13_val;
input  [18:0] data_14_val;
input  [18:0] data_15_val;
output  [14:0] ap_return_0;
output  [14:0] ap_return_1;
output  [14:0] ap_return_2;
output  [14:0] ap_return_3;
output  [14:0] ap_return_4;
output  [14:0] ap_return_5;
output  [14:0] ap_return_6;
output  [14:0] ap_return_7;
output  [14:0] ap_return_8;
output  [14:0] ap_return_9;
output  [14:0] ap_return_10;
output  [14:0] ap_return_11;
output  [14:0] ap_return_12;
output  [14:0] ap_return_13;
output  [14:0] ap_return_14;
output  [14:0] ap_return_15;
input   ap_rst;

wire   [7:0] trunc_ln46_fu_176_p1;
wire   [0:0] tmp_fu_168_p3;
wire   [10:0] tmp_s_fu_188_p4;
wire   [0:0] icmp_ln46_fu_204_p2;
wire   [0:0] xor_ln46_fu_198_p2;
wire   [0:0] and_ln46_fu_210_p2;
wire   [0:0] or_ln46_fu_224_p2;
wire   [14:0] select_ln46_16_fu_216_p3;
wire   [14:0] shl_ln_fu_180_p3;
wire   [0:0] icmp_ln45_fu_162_p2;
wire   [14:0] select_ln46_fu_230_p3;
wire   [7:0] trunc_ln46_1_fu_260_p1;
wire   [0:0] tmp_1_fu_252_p3;
wire   [10:0] tmp_2_fu_272_p4;
wire   [0:0] icmp_ln46_1_fu_288_p2;
wire   [0:0] xor_ln46_1_fu_282_p2;
wire   [0:0] and_ln46_1_fu_294_p2;
wire   [0:0] or_ln46_1_fu_308_p2;
wire   [14:0] select_ln46_17_fu_300_p3;
wire   [14:0] shl_ln46_1_fu_264_p3;
wire   [0:0] icmp_ln45_1_fu_246_p2;
wire   [14:0] select_ln46_1_fu_314_p3;
wire   [7:0] trunc_ln46_2_fu_344_p1;
wire   [0:0] tmp_3_fu_336_p3;
wire   [10:0] tmp_4_fu_356_p4;
wire   [0:0] icmp_ln46_2_fu_372_p2;
wire   [0:0] xor_ln46_2_fu_366_p2;
wire   [0:0] and_ln46_2_fu_378_p2;
wire   [0:0] or_ln46_2_fu_392_p2;
wire   [14:0] select_ln46_18_fu_384_p3;
wire   [14:0] shl_ln46_2_fu_348_p3;
wire   [0:0] icmp_ln45_2_fu_330_p2;
wire   [14:0] select_ln46_2_fu_398_p3;
wire   [7:0] trunc_ln46_3_fu_428_p1;
wire   [0:0] tmp_5_fu_420_p3;
wire   [10:0] tmp_6_fu_440_p4;
wire   [0:0] icmp_ln46_3_fu_456_p2;
wire   [0:0] xor_ln46_3_fu_450_p2;
wire   [0:0] and_ln46_3_fu_462_p2;
wire   [0:0] or_ln46_3_fu_476_p2;
wire   [14:0] select_ln46_19_fu_468_p3;
wire   [14:0] shl_ln46_3_fu_432_p3;
wire   [0:0] icmp_ln45_3_fu_414_p2;
wire   [14:0] select_ln46_3_fu_482_p3;
wire   [7:0] trunc_ln46_4_fu_512_p1;
wire   [0:0] tmp_7_fu_504_p3;
wire   [10:0] tmp_8_fu_524_p4;
wire   [0:0] icmp_ln46_4_fu_540_p2;
wire   [0:0] xor_ln46_4_fu_534_p2;
wire   [0:0] and_ln46_4_fu_546_p2;
wire   [0:0] or_ln46_4_fu_560_p2;
wire   [14:0] select_ln46_20_fu_552_p3;
wire   [14:0] shl_ln46_4_fu_516_p3;
wire   [0:0] icmp_ln45_4_fu_498_p2;
wire   [14:0] select_ln46_4_fu_566_p3;
wire   [7:0] trunc_ln46_5_fu_596_p1;
wire   [0:0] tmp_9_fu_588_p3;
wire   [10:0] tmp_10_fu_608_p4;
wire   [0:0] icmp_ln46_5_fu_624_p2;
wire   [0:0] xor_ln46_5_fu_618_p2;
wire   [0:0] and_ln46_5_fu_630_p2;
wire   [0:0] or_ln46_5_fu_644_p2;
wire   [14:0] select_ln46_21_fu_636_p3;
wire   [14:0] shl_ln46_5_fu_600_p3;
wire   [0:0] icmp_ln45_5_fu_582_p2;
wire   [14:0] select_ln46_5_fu_650_p3;
wire   [7:0] trunc_ln46_6_fu_680_p1;
wire   [0:0] tmp_11_fu_672_p3;
wire   [10:0] tmp_12_fu_692_p4;
wire   [0:0] icmp_ln46_6_fu_708_p2;
wire   [0:0] xor_ln46_6_fu_702_p2;
wire   [0:0] and_ln46_6_fu_714_p2;
wire   [0:0] or_ln46_6_fu_728_p2;
wire   [14:0] select_ln46_22_fu_720_p3;
wire   [14:0] shl_ln46_6_fu_684_p3;
wire   [0:0] icmp_ln45_6_fu_666_p2;
wire   [14:0] select_ln46_6_fu_734_p3;
wire   [7:0] trunc_ln46_7_fu_764_p1;
wire   [0:0] tmp_13_fu_756_p3;
wire   [10:0] tmp_14_fu_776_p4;
wire   [0:0] icmp_ln46_7_fu_792_p2;
wire   [0:0] xor_ln46_7_fu_786_p2;
wire   [0:0] and_ln46_7_fu_798_p2;
wire   [0:0] or_ln46_7_fu_812_p2;
wire   [14:0] select_ln46_23_fu_804_p3;
wire   [14:0] shl_ln46_7_fu_768_p3;
wire   [0:0] icmp_ln45_7_fu_750_p2;
wire   [14:0] select_ln46_7_fu_818_p3;
wire   [7:0] trunc_ln46_8_fu_848_p1;
wire   [0:0] tmp_15_fu_840_p3;
wire   [10:0] tmp_16_fu_860_p4;
wire   [0:0] icmp_ln46_8_fu_876_p2;
wire   [0:0] xor_ln46_8_fu_870_p2;
wire   [0:0] and_ln46_8_fu_882_p2;
wire   [0:0] or_ln46_8_fu_896_p2;
wire   [14:0] select_ln46_24_fu_888_p3;
wire   [14:0] shl_ln46_8_fu_852_p3;
wire   [0:0] icmp_ln45_8_fu_834_p2;
wire   [14:0] select_ln46_8_fu_902_p3;
wire   [7:0] trunc_ln46_9_fu_932_p1;
wire   [0:0] tmp_17_fu_924_p3;
wire   [10:0] tmp_18_fu_944_p4;
wire   [0:0] icmp_ln46_9_fu_960_p2;
wire   [0:0] xor_ln46_9_fu_954_p2;
wire   [0:0] and_ln46_9_fu_966_p2;
wire   [0:0] or_ln46_9_fu_980_p2;
wire   [14:0] select_ln46_25_fu_972_p3;
wire   [14:0] shl_ln46_9_fu_936_p3;
wire   [0:0] icmp_ln45_9_fu_918_p2;
wire   [14:0] select_ln46_9_fu_986_p3;
wire   [7:0] trunc_ln46_10_fu_1016_p1;
wire   [0:0] tmp_19_fu_1008_p3;
wire   [10:0] tmp_20_fu_1028_p4;
wire   [0:0] icmp_ln46_10_fu_1044_p2;
wire   [0:0] xor_ln46_10_fu_1038_p2;
wire   [0:0] and_ln46_10_fu_1050_p2;
wire   [0:0] or_ln46_10_fu_1064_p2;
wire   [14:0] select_ln46_26_fu_1056_p3;
wire   [14:0] shl_ln46_s_fu_1020_p3;
wire   [0:0] icmp_ln45_10_fu_1002_p2;
wire   [14:0] select_ln46_10_fu_1070_p3;
wire   [7:0] trunc_ln46_11_fu_1100_p1;
wire   [0:0] tmp_21_fu_1092_p3;
wire   [10:0] tmp_22_fu_1112_p4;
wire   [0:0] icmp_ln46_11_fu_1128_p2;
wire   [0:0] xor_ln46_11_fu_1122_p2;
wire   [0:0] and_ln46_11_fu_1134_p2;
wire   [0:0] or_ln46_11_fu_1148_p2;
wire   [14:0] select_ln46_27_fu_1140_p3;
wire   [14:0] shl_ln46_10_fu_1104_p3;
wire   [0:0] icmp_ln45_11_fu_1086_p2;
wire   [14:0] select_ln46_11_fu_1154_p3;
wire   [7:0] trunc_ln46_12_fu_1184_p1;
wire   [0:0] tmp_23_fu_1176_p3;
wire   [10:0] tmp_24_fu_1196_p4;
wire   [0:0] icmp_ln46_12_fu_1212_p2;
wire   [0:0] xor_ln46_12_fu_1206_p2;
wire   [0:0] and_ln46_12_fu_1218_p2;
wire   [0:0] or_ln46_12_fu_1232_p2;
wire   [14:0] select_ln46_28_fu_1224_p3;
wire   [14:0] shl_ln46_11_fu_1188_p3;
wire   [0:0] icmp_ln45_12_fu_1170_p2;
wire   [14:0] select_ln46_12_fu_1238_p3;
wire   [7:0] trunc_ln46_13_fu_1268_p1;
wire   [0:0] tmp_25_fu_1260_p3;
wire   [10:0] tmp_26_fu_1280_p4;
wire   [0:0] icmp_ln46_13_fu_1296_p2;
wire   [0:0] xor_ln46_13_fu_1290_p2;
wire   [0:0] and_ln46_13_fu_1302_p2;
wire   [0:0] or_ln46_13_fu_1316_p2;
wire   [14:0] select_ln46_29_fu_1308_p3;
wire   [14:0] shl_ln46_12_fu_1272_p3;
wire   [0:0] icmp_ln45_13_fu_1254_p2;
wire   [14:0] select_ln46_13_fu_1322_p3;
wire   [7:0] trunc_ln46_14_fu_1352_p1;
wire   [0:0] tmp_27_fu_1344_p3;
wire   [10:0] tmp_28_fu_1364_p4;
wire   [0:0] icmp_ln46_14_fu_1380_p2;
wire   [0:0] xor_ln46_14_fu_1374_p2;
wire   [0:0] and_ln46_14_fu_1386_p2;
wire   [0:0] or_ln46_14_fu_1400_p2;
wire   [14:0] select_ln46_30_fu_1392_p3;
wire   [14:0] shl_ln46_13_fu_1356_p3;
wire   [0:0] icmp_ln45_14_fu_1338_p2;
wire   [14:0] select_ln46_14_fu_1406_p3;
wire   [7:0] trunc_ln46_15_fu_1436_p1;
wire   [0:0] tmp_29_fu_1428_p3;
wire   [10:0] tmp_30_fu_1448_p4;
wire   [0:0] icmp_ln46_15_fu_1464_p2;
wire   [0:0] xor_ln46_15_fu_1458_p2;
wire   [0:0] and_ln46_15_fu_1470_p2;
wire   [0:0] or_ln46_15_fu_1484_p2;
wire   [14:0] select_ln46_31_fu_1476_p3;
wire   [14:0] shl_ln46_14_fu_1440_p3;
wire   [0:0] icmp_ln45_15_fu_1422_p2;
wire   [14:0] select_ln46_15_fu_1490_p3;
wire   [14:0] res_0_0_fu_238_p3;
wire   [14:0] res_1_0_fu_322_p3;
wire   [14:0] res_2_0_fu_406_p3;
wire   [14:0] res_3_0_fu_490_p3;
wire   [14:0] res_4_0_fu_574_p3;
wire   [14:0] res_5_0_fu_658_p3;
wire   [14:0] res_6_0_fu_742_p3;
wire   [14:0] res_7_0_fu_826_p3;
wire   [14:0] res_8_0_fu_910_p3;
wire   [14:0] res_9_0_fu_994_p3;
wire   [14:0] res_10_0_fu_1078_p3;
wire   [14:0] res_11_0_fu_1162_p3;
wire   [14:0] res_12_0_fu_1246_p3;
wire   [14:0] res_13_0_fu_1330_p3;
wire   [14:0] res_1445_0_fu_1414_p3;
wire   [14:0] res_15_0_fu_1498_p3;
wire    ap_ce_reg;

assign and_ln46_10_fu_1050_p2 = (xor_ln46_10_fu_1038_p2 & icmp_ln46_10_fu_1044_p2);

assign and_ln46_11_fu_1134_p2 = (xor_ln46_11_fu_1122_p2 & icmp_ln46_11_fu_1128_p2);

assign and_ln46_12_fu_1218_p2 = (xor_ln46_12_fu_1206_p2 & icmp_ln46_12_fu_1212_p2);

assign and_ln46_13_fu_1302_p2 = (xor_ln46_13_fu_1290_p2 & icmp_ln46_13_fu_1296_p2);

assign and_ln46_14_fu_1386_p2 = (xor_ln46_14_fu_1374_p2 & icmp_ln46_14_fu_1380_p2);

assign and_ln46_15_fu_1470_p2 = (xor_ln46_15_fu_1458_p2 & icmp_ln46_15_fu_1464_p2);

assign and_ln46_1_fu_294_p2 = (xor_ln46_1_fu_282_p2 & icmp_ln46_1_fu_288_p2);

assign and_ln46_2_fu_378_p2 = (xor_ln46_2_fu_366_p2 & icmp_ln46_2_fu_372_p2);

assign and_ln46_3_fu_462_p2 = (xor_ln46_3_fu_450_p2 & icmp_ln46_3_fu_456_p2);

assign and_ln46_4_fu_546_p2 = (xor_ln46_4_fu_534_p2 & icmp_ln46_4_fu_540_p2);

assign and_ln46_5_fu_630_p2 = (xor_ln46_5_fu_618_p2 & icmp_ln46_5_fu_624_p2);

assign and_ln46_6_fu_714_p2 = (xor_ln46_6_fu_702_p2 & icmp_ln46_6_fu_708_p2);

assign and_ln46_7_fu_798_p2 = (xor_ln46_7_fu_786_p2 & icmp_ln46_7_fu_792_p2);

assign and_ln46_8_fu_882_p2 = (xor_ln46_8_fu_870_p2 & icmp_ln46_8_fu_876_p2);

assign and_ln46_9_fu_966_p2 = (xor_ln46_9_fu_954_p2 & icmp_ln46_9_fu_960_p2);

assign and_ln46_fu_210_p2 = (xor_ln46_fu_198_p2 & icmp_ln46_fu_204_p2);

assign ap_ready = 1'b1;

assign icmp_ln46_10_fu_1044_p2 = ((tmp_20_fu_1028_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_11_fu_1128_p2 = ((tmp_22_fu_1112_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_12_fu_1212_p2 = ((tmp_24_fu_1196_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_13_fu_1296_p2 = ((tmp_26_fu_1280_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_14_fu_1380_p2 = ((tmp_28_fu_1364_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_15_fu_1464_p2 = ((tmp_30_fu_1448_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_1_fu_288_p2 = ((tmp_2_fu_272_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_2_fu_372_p2 = ((tmp_4_fu_356_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_3_fu_456_p2 = ((tmp_6_fu_440_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_4_fu_540_p2 = ((tmp_8_fu_524_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_5_fu_624_p2 = ((tmp_10_fu_608_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_6_fu_708_p2 = ((tmp_12_fu_692_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_7_fu_792_p2 = ((tmp_14_fu_776_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_8_fu_876_p2 = ((tmp_16_fu_860_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_9_fu_960_p2 = ((tmp_18_fu_944_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_204_p2 = ((tmp_s_fu_188_p4 != 11'd0) ? 1'b1 : 1'b0);

assign or_ln46_10_fu_1064_p2 = (tmp_19_fu_1008_p3 | and_ln46_10_fu_1050_p2);

assign or_ln46_11_fu_1148_p2 = (tmp_21_fu_1092_p3 | and_ln46_11_fu_1134_p2);

assign or_ln46_12_fu_1232_p2 = (tmp_23_fu_1176_p3 | and_ln46_12_fu_1218_p2);

assign or_ln46_13_fu_1316_p2 = (tmp_25_fu_1260_p3 | and_ln46_13_fu_1302_p2);

assign or_ln46_14_fu_1400_p2 = (tmp_27_fu_1344_p3 | and_ln46_14_fu_1386_p2);

assign or_ln46_15_fu_1484_p2 = (tmp_29_fu_1428_p3 | and_ln46_15_fu_1470_p2);

assign or_ln46_1_fu_308_p2 = (tmp_1_fu_252_p3 | and_ln46_1_fu_294_p2);

assign or_ln46_2_fu_392_p2 = (tmp_3_fu_336_p3 | and_ln46_2_fu_378_p2);

assign or_ln46_3_fu_476_p2 = (tmp_5_fu_420_p3 | and_ln46_3_fu_462_p2);

assign or_ln46_4_fu_560_p2 = (tmp_7_fu_504_p3 | and_ln46_4_fu_546_p2);

assign or_ln46_5_fu_644_p2 = (tmp_9_fu_588_p3 | and_ln46_5_fu_630_p2);

assign or_ln46_6_fu_728_p2 = (tmp_11_fu_672_p3 | and_ln46_6_fu_714_p2);

assign or_ln46_7_fu_812_p2 = (tmp_13_fu_756_p3 | and_ln46_7_fu_798_p2);

assign or_ln46_8_fu_896_p2 = (tmp_15_fu_840_p3 | and_ln46_8_fu_882_p2);

assign or_ln46_9_fu_980_p2 = (tmp_17_fu_924_p3 | and_ln46_9_fu_966_p2);

assign or_ln46_fu_224_p2 = (tmp_fu_168_p3 | and_ln46_fu_210_p2);

assign res_0_0_fu_238_p3 = ((icmp_ln45_fu_162_p2[0:0] == 1'b1) ? select_ln46_fu_230_p3 : 15'd0);

assign res_10_0_fu_1078_p3 = ((icmp_ln45_10_fu_1002_p2[0:0] == 1'b1) ? select_ln46_10_fu_1070_p3 : 15'd0);

assign res_11_0_fu_1162_p3 = ((icmp_ln45_11_fu_1086_p2[0:0] == 1'b1) ? select_ln46_11_fu_1154_p3 : 15'd0);

assign res_12_0_fu_1246_p3 = ((icmp_ln45_12_fu_1170_p2[0:0] == 1'b1) ? select_ln46_12_fu_1238_p3 : 15'd0);

assign res_13_0_fu_1330_p3 = ((icmp_ln45_13_fu_1254_p2[0:0] == 1'b1) ? select_ln46_13_fu_1322_p3 : 15'd0);

assign res_1445_0_fu_1414_p3 = ((icmp_ln45_14_fu_1338_p2[0:0] == 1'b1) ? select_ln46_14_fu_1406_p3 : 15'd0);

assign res_15_0_fu_1498_p3 = ((icmp_ln45_15_fu_1422_p2[0:0] == 1'b1) ? select_ln46_15_fu_1490_p3 : 15'd0);

assign res_1_0_fu_322_p3 = ((icmp_ln45_1_fu_246_p2[0:0] == 1'b1) ? select_ln46_1_fu_314_p3 : 15'd0);

assign res_2_0_fu_406_p3 = ((icmp_ln45_2_fu_330_p2[0:0] == 1'b1) ? select_ln46_2_fu_398_p3 : 15'd0);

assign res_3_0_fu_490_p3 = ((icmp_ln45_3_fu_414_p2[0:0] == 1'b1) ? select_ln46_3_fu_482_p3 : 15'd0);

assign res_4_0_fu_574_p3 = ((icmp_ln45_4_fu_498_p2[0:0] == 1'b1) ? select_ln46_4_fu_566_p3 : 15'd0);

assign res_5_0_fu_658_p3 = ((icmp_ln45_5_fu_582_p2[0:0] == 1'b1) ? select_ln46_5_fu_650_p3 : 15'd0);

assign res_6_0_fu_742_p3 = ((icmp_ln45_6_fu_666_p2[0:0] == 1'b1) ? select_ln46_6_fu_734_p3 : 15'd0);

assign res_7_0_fu_826_p3 = ((icmp_ln45_7_fu_750_p2[0:0] == 1'b1) ? select_ln46_7_fu_818_p3 : 15'd0);

assign res_8_0_fu_910_p3 = ((icmp_ln45_8_fu_834_p2[0:0] == 1'b1) ? select_ln46_8_fu_902_p3 : 15'd0);

assign res_9_0_fu_994_p3 = ((icmp_ln45_9_fu_918_p2[0:0] == 1'b1) ? select_ln46_9_fu_986_p3 : 15'd0);

assign select_ln46_10_fu_1070_p3 = ((or_ln46_10_fu_1064_p2[0:0] == 1'b1) ? select_ln46_26_fu_1056_p3 : shl_ln46_s_fu_1020_p3);

assign select_ln46_11_fu_1154_p3 = ((or_ln46_11_fu_1148_p2[0:0] == 1'b1) ? select_ln46_27_fu_1140_p3 : shl_ln46_10_fu_1104_p3);

assign select_ln46_12_fu_1238_p3 = ((or_ln46_12_fu_1232_p2[0:0] == 1'b1) ? select_ln46_28_fu_1224_p3 : shl_ln46_11_fu_1188_p3);

assign select_ln46_13_fu_1322_p3 = ((or_ln46_13_fu_1316_p2[0:0] == 1'b1) ? select_ln46_29_fu_1308_p3 : shl_ln46_12_fu_1272_p3);

assign select_ln46_14_fu_1406_p3 = ((or_ln46_14_fu_1400_p2[0:0] == 1'b1) ? select_ln46_30_fu_1392_p3 : shl_ln46_13_fu_1356_p3);

assign select_ln46_15_fu_1490_p3 = ((or_ln46_15_fu_1484_p2[0:0] == 1'b1) ? select_ln46_31_fu_1476_p3 : shl_ln46_14_fu_1440_p3);

assign select_ln46_16_fu_216_p3 = ((and_ln46_fu_210_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_17_fu_300_p3 = ((and_ln46_1_fu_294_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_18_fu_384_p3 = ((and_ln46_2_fu_378_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_19_fu_468_p3 = ((and_ln46_3_fu_462_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_1_fu_314_p3 = ((or_ln46_1_fu_308_p2[0:0] == 1'b1) ? select_ln46_17_fu_300_p3 : shl_ln46_1_fu_264_p3);

assign select_ln46_20_fu_552_p3 = ((and_ln46_4_fu_546_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_21_fu_636_p3 = ((and_ln46_5_fu_630_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_22_fu_720_p3 = ((and_ln46_6_fu_714_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_23_fu_804_p3 = ((and_ln46_7_fu_798_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_24_fu_888_p3 = ((and_ln46_8_fu_882_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_25_fu_972_p3 = ((and_ln46_9_fu_966_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_26_fu_1056_p3 = ((and_ln46_10_fu_1050_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_27_fu_1140_p3 = ((and_ln46_11_fu_1134_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_28_fu_1224_p3 = ((and_ln46_12_fu_1218_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_29_fu_1308_p3 = ((and_ln46_13_fu_1302_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_2_fu_398_p3 = ((or_ln46_2_fu_392_p2[0:0] == 1'b1) ? select_ln46_18_fu_384_p3 : shl_ln46_2_fu_348_p3);

assign select_ln46_30_fu_1392_p3 = ((and_ln46_14_fu_1386_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_31_fu_1476_p3 = ((and_ln46_15_fu_1470_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_3_fu_482_p3 = ((or_ln46_3_fu_476_p2[0:0] == 1'b1) ? select_ln46_19_fu_468_p3 : shl_ln46_3_fu_432_p3);

assign select_ln46_4_fu_566_p3 = ((or_ln46_4_fu_560_p2[0:0] == 1'b1) ? select_ln46_20_fu_552_p3 : shl_ln46_4_fu_516_p3);

assign select_ln46_5_fu_650_p3 = ((or_ln46_5_fu_644_p2[0:0] == 1'b1) ? select_ln46_21_fu_636_p3 : shl_ln46_5_fu_600_p3);

assign select_ln46_6_fu_734_p3 = ((or_ln46_6_fu_728_p2[0:0] == 1'b1) ? select_ln46_22_fu_720_p3 : shl_ln46_6_fu_684_p3);

assign select_ln46_7_fu_818_p3 = ((or_ln46_7_fu_812_p2[0:0] == 1'b1) ? select_ln46_23_fu_804_p3 : shl_ln46_7_fu_768_p3);

assign select_ln46_8_fu_902_p3 = ((or_ln46_8_fu_896_p2[0:0] == 1'b1) ? select_ln46_24_fu_888_p3 : shl_ln46_8_fu_852_p3);

assign select_ln46_9_fu_986_p3 = ((or_ln46_9_fu_980_p2[0:0] == 1'b1) ? select_ln46_25_fu_972_p3 : shl_ln46_9_fu_936_p3);

assign select_ln46_fu_230_p3 = ((or_ln46_fu_224_p2[0:0] == 1'b1) ? select_ln46_16_fu_216_p3 : shl_ln_fu_180_p3);

assign shl_ln46_10_fu_1104_p3 = {{trunc_ln46_11_fu_1100_p1}, {7'd0}};

assign shl_ln46_11_fu_1188_p3 = {{trunc_ln46_12_fu_1184_p1}, {7'd0}};

assign shl_ln46_12_fu_1272_p3 = {{trunc_ln46_13_fu_1268_p1}, {7'd0}};

assign shl_ln46_13_fu_1356_p3 = {{trunc_ln46_14_fu_1352_p1}, {7'd0}};

assign shl_ln46_14_fu_1440_p3 = {{trunc_ln46_15_fu_1436_p1}, {7'd0}};

assign shl_ln46_1_fu_264_p3 = {{trunc_ln46_1_fu_260_p1}, {7'd0}};

assign shl_ln46_2_fu_348_p3 = {{trunc_ln46_2_fu_344_p1}, {7'd0}};

assign shl_ln46_3_fu_432_p3 = {{trunc_ln46_3_fu_428_p1}, {7'd0}};

assign shl_ln46_4_fu_516_p3 = {{trunc_ln46_4_fu_512_p1}, {7'd0}};

assign shl_ln46_5_fu_600_p3 = {{trunc_ln46_5_fu_596_p1}, {7'd0}};

assign shl_ln46_6_fu_684_p3 = {{trunc_ln46_6_fu_680_p1}, {7'd0}};

assign shl_ln46_7_fu_768_p3 = {{trunc_ln46_7_fu_764_p1}, {7'd0}};

assign shl_ln46_8_fu_852_p3 = {{trunc_ln46_8_fu_848_p1}, {7'd0}};

assign shl_ln46_9_fu_936_p3 = {{trunc_ln46_9_fu_932_p1}, {7'd0}};

assign shl_ln46_s_fu_1020_p3 = {{trunc_ln46_10_fu_1016_p1}, {7'd0}};

assign shl_ln_fu_180_p3 = {{trunc_ln46_fu_176_p1}, {7'd0}};

assign tmp_10_fu_608_p4 = {{data_5_val[18:8]}};

assign tmp_11_fu_672_p3 = data_6_val[32'd18];

assign tmp_12_fu_692_p4 = {{data_6_val[18:8]}};

assign tmp_13_fu_756_p3 = data_7_val[32'd18];

assign tmp_14_fu_776_p4 = {{data_7_val[18:8]}};

assign tmp_15_fu_840_p3 = data_8_val[32'd18];

assign tmp_16_fu_860_p4 = {{data_8_val[18:8]}};

assign tmp_17_fu_924_p3 = data_9_val[32'd18];

assign tmp_18_fu_944_p4 = {{data_9_val[18:8]}};

assign tmp_19_fu_1008_p3 = data_10_val[32'd18];

assign tmp_1_fu_252_p3 = data_1_val[32'd18];

assign tmp_20_fu_1028_p4 = {{data_10_val[18:8]}};

assign tmp_21_fu_1092_p3 = data_11_val[32'd18];

assign tmp_22_fu_1112_p4 = {{data_11_val[18:8]}};

assign tmp_23_fu_1176_p3 = data_12_val[32'd18];

assign tmp_24_fu_1196_p4 = {{data_12_val[18:8]}};

assign tmp_25_fu_1260_p3 = data_13_val[32'd18];

assign tmp_26_fu_1280_p4 = {{data_13_val[18:8]}};

assign tmp_27_fu_1344_p3 = data_14_val[32'd18];

assign tmp_28_fu_1364_p4 = {{data_14_val[18:8]}};

assign tmp_29_fu_1428_p3 = data_15_val[32'd18];

assign tmp_2_fu_272_p4 = {{data_1_val[18:8]}};

assign tmp_30_fu_1448_p4 = {{data_15_val[18:8]}};

assign tmp_3_fu_336_p3 = data_2_val[32'd18];

assign tmp_4_fu_356_p4 = {{data_2_val[18:8]}};

assign tmp_5_fu_420_p3 = data_3_val[32'd18];

assign tmp_6_fu_440_p4 = {{data_3_val[18:8]}};

assign tmp_7_fu_504_p3 = data_4_val[32'd18];

assign tmp_8_fu_524_p4 = {{data_4_val[18:8]}};

assign tmp_9_fu_588_p3 = data_5_val[32'd18];

assign tmp_fu_168_p3 = data_0_val[32'd18];

assign tmp_s_fu_188_p4 = {{data_0_val[18:8]}};

assign trunc_ln46_10_fu_1016_p1 = data_10_val[7:0];

assign trunc_ln46_11_fu_1100_p1 = data_11_val[7:0];

assign trunc_ln46_12_fu_1184_p1 = data_12_val[7:0];

assign trunc_ln46_13_fu_1268_p1 = data_13_val[7:0];

assign trunc_ln46_14_fu_1352_p1 = data_14_val[7:0];

assign trunc_ln46_15_fu_1436_p1 = data_15_val[7:0];

assign trunc_ln46_1_fu_260_p1 = data_1_val[7:0];

assign trunc_ln46_2_fu_344_p1 = data_2_val[7:0];

assign trunc_ln46_3_fu_428_p1 = data_3_val[7:0];

assign trunc_ln46_4_fu_512_p1 = data_4_val[7:0];

assign trunc_ln46_5_fu_596_p1 = data_5_val[7:0];

assign trunc_ln46_6_fu_680_p1 = data_6_val[7:0];

assign trunc_ln46_7_fu_764_p1 = data_7_val[7:0];

assign trunc_ln46_8_fu_848_p1 = data_8_val[7:0];

assign trunc_ln46_9_fu_932_p1 = data_9_val[7:0];

assign trunc_ln46_fu_176_p1 = data_0_val[7:0];

assign xor_ln46_10_fu_1038_p2 = (tmp_19_fu_1008_p3 ^ 1'd1);

assign xor_ln46_11_fu_1122_p2 = (tmp_21_fu_1092_p3 ^ 1'd1);

assign xor_ln46_12_fu_1206_p2 = (tmp_23_fu_1176_p3 ^ 1'd1);

assign xor_ln46_13_fu_1290_p2 = (tmp_25_fu_1260_p3 ^ 1'd1);

assign xor_ln46_14_fu_1374_p2 = (tmp_27_fu_1344_p3 ^ 1'd1);

assign xor_ln46_15_fu_1458_p2 = (tmp_29_fu_1428_p3 ^ 1'd1);

assign xor_ln46_1_fu_282_p2 = (tmp_1_fu_252_p3 ^ 1'd1);

assign xor_ln46_2_fu_366_p2 = (tmp_3_fu_336_p3 ^ 1'd1);

assign xor_ln46_3_fu_450_p2 = (tmp_5_fu_420_p3 ^ 1'd1);

assign xor_ln46_4_fu_534_p2 = (tmp_7_fu_504_p3 ^ 1'd1);

assign xor_ln46_5_fu_618_p2 = (tmp_9_fu_588_p3 ^ 1'd1);

assign xor_ln46_6_fu_702_p2 = (tmp_11_fu_672_p3 ^ 1'd1);

assign xor_ln46_7_fu_786_p2 = (tmp_13_fu_756_p3 ^ 1'd1);

assign xor_ln46_8_fu_870_p2 = (tmp_15_fu_840_p3 ^ 1'd1);

assign xor_ln46_9_fu_954_p2 = (tmp_17_fu_924_p3 ^ 1'd1);

assign xor_ln46_fu_198_p2 = (tmp_fu_168_p3 ^ 1'd1);

assign ap_return_0 = res_0_0_fu_238_p3;

assign ap_return_1 = res_1_0_fu_322_p3;

assign ap_return_10 = res_10_0_fu_1078_p3;

assign ap_return_11 = res_11_0_fu_1162_p3;

assign ap_return_12 = res_12_0_fu_1246_p3;

assign ap_return_13 = res_13_0_fu_1330_p3;

assign ap_return_14 = res_1445_0_fu_1414_p3;

assign ap_return_15 = res_15_0_fu_1498_p3;

assign ap_return_2 = res_2_0_fu_406_p3;

assign ap_return_3 = res_3_0_fu_490_p3;

assign ap_return_4 = res_4_0_fu_574_p3;

assign ap_return_5 = res_5_0_fu_658_p3;

assign ap_return_6 = res_6_0_fu_742_p3;

assign ap_return_7 = res_7_0_fu_826_p3;

assign ap_return_8 = res_8_0_fu_910_p3;

assign ap_return_9 = res_9_0_fu_994_p3;

assign icmp_ln45_10_fu_1002_p2 = (($signed(data_10_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_11_fu_1086_p2 = (($signed(data_11_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_12_fu_1170_p2 = (($signed(data_12_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_13_fu_1254_p2 = (($signed(data_13_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_14_fu_1338_p2 = (($signed(data_14_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_15_fu_1422_p2 = (($signed(data_15_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_1_fu_246_p2 = (($signed(data_1_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_330_p2 = (($signed(data_2_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_3_fu_414_p2 = (($signed(data_3_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_4_fu_498_p2 = (($signed(data_4_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_5_fu_582_p2 = (($signed(data_5_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_6_fu_666_p2 = (($signed(data_6_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_7_fu_750_p2 = (($signed(data_7_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_8_fu_834_p2 = (($signed(data_8_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_9_fu_918_p2 = (($signed(data_9_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_162_p2 = (($signed(data_0_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

endmodule //Topo2A_AD_proj_relu_ap_fixed_19_11_5_3_0_ap_ufixed_15_0_4_0_0_relu_config7_s
