// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Topo2A_AD_proj_relu_ap_fixed_19_11_5_3_0_ap_ufixed_15_0_4_0_0_relu_config4_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_rst
);


output   ap_ready;
input  [18:0] data_0_val;
input  [18:0] data_1_val;
input  [18:0] data_2_val;
input  [18:0] data_3_val;
input  [18:0] data_4_val;
input  [18:0] data_5_val;
input  [18:0] data_6_val;
input  [18:0] data_7_val;
input  [18:0] data_8_val;
input  [18:0] data_9_val;
input  [18:0] data_10_val;
input  [18:0] data_11_val;
input  [18:0] data_12_val;
input  [18:0] data_13_val;
input  [18:0] data_14_val;
input  [18:0] data_15_val;
input  [18:0] data_16_val;
input  [18:0] data_17_val;
input  [18:0] data_18_val;
input  [18:0] data_19_val;
input  [18:0] data_20_val;
input  [18:0] data_21_val;
input  [18:0] data_22_val;
input  [18:0] data_23_val;
input  [18:0] data_24_val;
input  [18:0] data_25_val;
input  [18:0] data_26_val;
input  [18:0] data_27_val;
input  [18:0] data_28_val;
input  [18:0] data_29_val;
input  [18:0] data_30_val;
input  [18:0] data_31_val;
output  [14:0] ap_return_0;
output  [14:0] ap_return_1;
output  [14:0] ap_return_2;
output  [14:0] ap_return_3;
output  [14:0] ap_return_4;
output  [14:0] ap_return_5;
output  [14:0] ap_return_6;
output  [14:0] ap_return_7;
output  [14:0] ap_return_8;
output  [14:0] ap_return_9;
output  [14:0] ap_return_10;
output  [14:0] ap_return_11;
output  [14:0] ap_return_12;
output  [14:0] ap_return_13;
output  [14:0] ap_return_14;
output  [14:0] ap_return_15;
output  [14:0] ap_return_16;
output  [14:0] ap_return_17;
output  [14:0] ap_return_18;
output  [14:0] ap_return_19;
output  [14:0] ap_return_20;
output  [14:0] ap_return_21;
output  [14:0] ap_return_22;
output  [14:0] ap_return_23;
output  [14:0] ap_return_24;
output  [14:0] ap_return_25;
output  [14:0] ap_return_26;
output  [14:0] ap_return_27;
output  [14:0] ap_return_28;
output  [14:0] ap_return_29;
output  [14:0] ap_return_30;
output  [14:0] ap_return_31;
input   ap_rst;

wire   [7:0] trunc_ln46_fu_304_p1;
wire   [0:0] tmp_fu_296_p3;
wire   [10:0] tmp_1_fu_316_p4;
wire   [0:0] icmp_ln46_fu_332_p2;
wire   [0:0] xor_ln46_fu_326_p2;
wire   [0:0] and_ln46_fu_338_p2;
wire   [0:0] or_ln46_fu_352_p2;
wire   [14:0] select_ln46_47_fu_344_p3;
wire   [14:0] shl_ln_fu_308_p3;
wire   [0:0] icmp_ln45_fu_290_p2;
wire   [14:0] select_ln46_fu_358_p3;
wire   [7:0] trunc_ln46_16_fu_388_p1;
wire   [0:0] tmp_30_fu_380_p3;
wire   [10:0] tmp_s_fu_400_p4;
wire   [0:0] icmp_ln46_16_fu_416_p2;
wire   [0:0] xor_ln46_16_fu_410_p2;
wire   [0:0] and_ln46_16_fu_422_p2;
wire   [0:0] or_ln46_16_fu_436_p2;
wire   [14:0] select_ln46_48_fu_428_p3;
wire   [14:0] shl_ln46_s_fu_392_p3;
wire   [0:0] icmp_ln45_16_fu_374_p2;
wire   [14:0] select_ln46_16_fu_442_p3;
wire   [7:0] trunc_ln46_17_fu_472_p1;
wire   [0:0] tmp_31_fu_464_p3;
wire   [10:0] tmp_32_fu_484_p4;
wire   [0:0] icmp_ln46_17_fu_500_p2;
wire   [0:0] xor_ln46_17_fu_494_p2;
wire   [0:0] and_ln46_17_fu_506_p2;
wire   [0:0] or_ln46_17_fu_520_p2;
wire   [14:0] select_ln46_49_fu_512_p3;
wire   [14:0] shl_ln46_15_fu_476_p3;
wire   [0:0] icmp_ln45_17_fu_458_p2;
wire   [14:0] select_ln46_17_fu_526_p3;
wire   [7:0] trunc_ln46_18_fu_556_p1;
wire   [0:0] tmp_33_fu_548_p3;
wire   [10:0] tmp_34_fu_568_p4;
wire   [0:0] icmp_ln46_18_fu_584_p2;
wire   [0:0] xor_ln46_18_fu_578_p2;
wire   [0:0] and_ln46_18_fu_590_p2;
wire   [0:0] or_ln46_18_fu_604_p2;
wire   [14:0] select_ln46_50_fu_596_p3;
wire   [14:0] shl_ln46_16_fu_560_p3;
wire   [0:0] icmp_ln45_18_fu_542_p2;
wire   [14:0] select_ln46_18_fu_610_p3;
wire   [7:0] trunc_ln46_19_fu_640_p1;
wire   [0:0] tmp_35_fu_632_p3;
wire   [10:0] tmp_36_fu_652_p4;
wire   [0:0] icmp_ln46_19_fu_668_p2;
wire   [0:0] xor_ln46_19_fu_662_p2;
wire   [0:0] and_ln46_19_fu_674_p2;
wire   [0:0] or_ln46_19_fu_688_p2;
wire   [14:0] select_ln46_51_fu_680_p3;
wire   [14:0] shl_ln46_17_fu_644_p3;
wire   [0:0] icmp_ln45_19_fu_626_p2;
wire   [14:0] select_ln46_19_fu_694_p3;
wire   [7:0] trunc_ln46_20_fu_724_p1;
wire   [0:0] tmp_37_fu_716_p3;
wire   [10:0] tmp_38_fu_736_p4;
wire   [0:0] icmp_ln46_20_fu_752_p2;
wire   [0:0] xor_ln46_20_fu_746_p2;
wire   [0:0] and_ln46_20_fu_758_p2;
wire   [0:0] or_ln46_20_fu_772_p2;
wire   [14:0] select_ln46_52_fu_764_p3;
wire   [14:0] shl_ln46_18_fu_728_p3;
wire   [0:0] icmp_ln45_20_fu_710_p2;
wire   [14:0] select_ln46_20_fu_778_p3;
wire   [7:0] trunc_ln46_21_fu_808_p1;
wire   [0:0] tmp_39_fu_800_p3;
wire   [10:0] tmp_40_fu_820_p4;
wire   [0:0] icmp_ln46_21_fu_836_p2;
wire   [0:0] xor_ln46_21_fu_830_p2;
wire   [0:0] and_ln46_21_fu_842_p2;
wire   [0:0] or_ln46_21_fu_856_p2;
wire   [14:0] select_ln46_53_fu_848_p3;
wire   [14:0] shl_ln46_19_fu_812_p3;
wire   [0:0] icmp_ln45_21_fu_794_p2;
wire   [14:0] select_ln46_21_fu_862_p3;
wire   [7:0] trunc_ln46_22_fu_892_p1;
wire   [0:0] tmp_41_fu_884_p3;
wire   [10:0] tmp_42_fu_904_p4;
wire   [0:0] icmp_ln46_22_fu_920_p2;
wire   [0:0] xor_ln46_22_fu_914_p2;
wire   [0:0] and_ln46_22_fu_926_p2;
wire   [0:0] or_ln46_22_fu_940_p2;
wire   [14:0] select_ln46_54_fu_932_p3;
wire   [14:0] shl_ln46_20_fu_896_p3;
wire   [0:0] icmp_ln45_22_fu_878_p2;
wire   [14:0] select_ln46_22_fu_946_p3;
wire   [7:0] trunc_ln46_23_fu_976_p1;
wire   [0:0] tmp_43_fu_968_p3;
wire   [10:0] tmp_44_fu_988_p4;
wire   [0:0] icmp_ln46_23_fu_1004_p2;
wire   [0:0] xor_ln46_23_fu_998_p2;
wire   [0:0] and_ln46_23_fu_1010_p2;
wire   [0:0] or_ln46_23_fu_1024_p2;
wire   [14:0] select_ln46_55_fu_1016_p3;
wire   [14:0] shl_ln46_21_fu_980_p3;
wire   [0:0] icmp_ln45_23_fu_962_p2;
wire   [14:0] select_ln46_23_fu_1030_p3;
wire   [7:0] trunc_ln46_24_fu_1060_p1;
wire   [0:0] tmp_45_fu_1052_p3;
wire   [10:0] tmp_46_fu_1072_p4;
wire   [0:0] icmp_ln46_24_fu_1088_p2;
wire   [0:0] xor_ln46_24_fu_1082_p2;
wire   [0:0] and_ln46_24_fu_1094_p2;
wire   [0:0] or_ln46_24_fu_1108_p2;
wire   [14:0] select_ln46_56_fu_1100_p3;
wire   [14:0] shl_ln46_22_fu_1064_p3;
wire   [0:0] icmp_ln45_24_fu_1046_p2;
wire   [14:0] select_ln46_24_fu_1114_p3;
wire   [7:0] trunc_ln46_25_fu_1144_p1;
wire   [0:0] tmp_47_fu_1136_p3;
wire   [10:0] tmp_48_fu_1156_p4;
wire   [0:0] icmp_ln46_25_fu_1172_p2;
wire   [0:0] xor_ln46_25_fu_1166_p2;
wire   [0:0] and_ln46_25_fu_1178_p2;
wire   [0:0] or_ln46_25_fu_1192_p2;
wire   [14:0] select_ln46_57_fu_1184_p3;
wire   [14:0] shl_ln46_23_fu_1148_p3;
wire   [0:0] icmp_ln45_25_fu_1130_p2;
wire   [14:0] select_ln46_25_fu_1198_p3;
wire   [7:0] trunc_ln46_26_fu_1228_p1;
wire   [0:0] tmp_49_fu_1220_p3;
wire   [10:0] tmp_50_fu_1240_p4;
wire   [0:0] icmp_ln46_26_fu_1256_p2;
wire   [0:0] xor_ln46_26_fu_1250_p2;
wire   [0:0] and_ln46_26_fu_1262_p2;
wire   [0:0] or_ln46_26_fu_1276_p2;
wire   [14:0] select_ln46_58_fu_1268_p3;
wire   [14:0] shl_ln46_24_fu_1232_p3;
wire   [0:0] icmp_ln45_26_fu_1214_p2;
wire   [14:0] select_ln46_26_fu_1282_p3;
wire   [7:0] trunc_ln46_27_fu_1312_p1;
wire   [0:0] tmp_51_fu_1304_p3;
wire   [10:0] tmp_52_fu_1324_p4;
wire   [0:0] icmp_ln46_27_fu_1340_p2;
wire   [0:0] xor_ln46_27_fu_1334_p2;
wire   [0:0] and_ln46_27_fu_1346_p2;
wire   [0:0] or_ln46_27_fu_1360_p2;
wire   [14:0] select_ln46_59_fu_1352_p3;
wire   [14:0] shl_ln46_25_fu_1316_p3;
wire   [0:0] icmp_ln45_27_fu_1298_p2;
wire   [14:0] select_ln46_27_fu_1366_p3;
wire   [7:0] trunc_ln46_28_fu_1396_p1;
wire   [0:0] tmp_53_fu_1388_p3;
wire   [10:0] tmp_54_fu_1408_p4;
wire   [0:0] icmp_ln46_28_fu_1424_p2;
wire   [0:0] xor_ln46_28_fu_1418_p2;
wire   [0:0] and_ln46_28_fu_1430_p2;
wire   [0:0] or_ln46_28_fu_1444_p2;
wire   [14:0] select_ln46_60_fu_1436_p3;
wire   [14:0] shl_ln46_26_fu_1400_p3;
wire   [0:0] icmp_ln45_28_fu_1382_p2;
wire   [14:0] select_ln46_28_fu_1450_p3;
wire   [7:0] trunc_ln46_29_fu_1480_p1;
wire   [0:0] tmp_55_fu_1472_p3;
wire   [10:0] tmp_56_fu_1492_p4;
wire   [0:0] icmp_ln46_29_fu_1508_p2;
wire   [0:0] xor_ln46_29_fu_1502_p2;
wire   [0:0] and_ln46_29_fu_1514_p2;
wire   [0:0] or_ln46_29_fu_1528_p2;
wire   [14:0] select_ln46_61_fu_1520_p3;
wire   [14:0] shl_ln46_27_fu_1484_p3;
wire   [0:0] icmp_ln45_29_fu_1466_p2;
wire   [14:0] select_ln46_29_fu_1534_p3;
wire   [7:0] trunc_ln46_30_fu_1564_p1;
wire   [0:0] tmp_57_fu_1556_p3;
wire   [10:0] tmp_58_fu_1576_p4;
wire   [0:0] icmp_ln46_30_fu_1592_p2;
wire   [0:0] xor_ln46_30_fu_1586_p2;
wire   [0:0] and_ln46_30_fu_1598_p2;
wire   [0:0] or_ln46_30_fu_1612_p2;
wire   [14:0] select_ln46_62_fu_1604_p3;
wire   [14:0] shl_ln46_28_fu_1568_p3;
wire   [0:0] icmp_ln45_30_fu_1550_p2;
wire   [14:0] select_ln46_30_fu_1618_p3;
wire   [7:0] trunc_ln46_31_fu_1648_p1;
wire   [0:0] tmp_59_fu_1640_p3;
wire   [10:0] tmp_60_fu_1660_p4;
wire   [0:0] icmp_ln46_31_fu_1676_p2;
wire   [0:0] xor_ln46_31_fu_1670_p2;
wire   [0:0] and_ln46_31_fu_1682_p2;
wire   [0:0] or_ln46_31_fu_1696_p2;
wire   [14:0] select_ln46_63_fu_1688_p3;
wire   [14:0] shl_ln46_29_fu_1652_p3;
wire   [0:0] icmp_ln45_31_fu_1634_p2;
wire   [14:0] select_ln46_31_fu_1702_p3;
wire   [7:0] trunc_ln46_32_fu_1732_p1;
wire   [0:0] tmp_61_fu_1724_p3;
wire   [10:0] tmp_62_fu_1744_p4;
wire   [0:0] icmp_ln46_32_fu_1760_p2;
wire   [0:0] xor_ln46_32_fu_1754_p2;
wire   [0:0] and_ln46_32_fu_1766_p2;
wire   [0:0] or_ln46_32_fu_1780_p2;
wire   [14:0] select_ln46_64_fu_1772_p3;
wire   [14:0] shl_ln46_30_fu_1736_p3;
wire   [0:0] icmp_ln45_32_fu_1718_p2;
wire   [14:0] select_ln46_32_fu_1786_p3;
wire   [7:0] trunc_ln46_33_fu_1816_p1;
wire   [0:0] tmp_63_fu_1808_p3;
wire   [10:0] tmp_64_fu_1828_p4;
wire   [0:0] icmp_ln46_33_fu_1844_p2;
wire   [0:0] xor_ln46_33_fu_1838_p2;
wire   [0:0] and_ln46_33_fu_1850_p2;
wire   [0:0] or_ln46_33_fu_1864_p2;
wire   [14:0] select_ln46_65_fu_1856_p3;
wire   [14:0] shl_ln46_31_fu_1820_p3;
wire   [0:0] icmp_ln45_33_fu_1802_p2;
wire   [14:0] select_ln46_33_fu_1870_p3;
wire   [7:0] trunc_ln46_34_fu_1900_p1;
wire   [0:0] tmp_65_fu_1892_p3;
wire   [10:0] tmp_66_fu_1912_p4;
wire   [0:0] icmp_ln46_34_fu_1928_p2;
wire   [0:0] xor_ln46_34_fu_1922_p2;
wire   [0:0] and_ln46_34_fu_1934_p2;
wire   [0:0] or_ln46_34_fu_1948_p2;
wire   [14:0] select_ln46_66_fu_1940_p3;
wire   [14:0] shl_ln46_32_fu_1904_p3;
wire   [0:0] icmp_ln45_34_fu_1886_p2;
wire   [14:0] select_ln46_34_fu_1954_p3;
wire   [7:0] trunc_ln46_35_fu_1984_p1;
wire   [0:0] tmp_67_fu_1976_p3;
wire   [10:0] tmp_68_fu_1996_p4;
wire   [0:0] icmp_ln46_35_fu_2012_p2;
wire   [0:0] xor_ln46_35_fu_2006_p2;
wire   [0:0] and_ln46_35_fu_2018_p2;
wire   [0:0] or_ln46_35_fu_2032_p2;
wire   [14:0] select_ln46_67_fu_2024_p3;
wire   [14:0] shl_ln46_33_fu_1988_p3;
wire   [0:0] icmp_ln45_35_fu_1970_p2;
wire   [14:0] select_ln46_35_fu_2038_p3;
wire   [7:0] trunc_ln46_36_fu_2068_p1;
wire   [0:0] tmp_69_fu_2060_p3;
wire   [10:0] tmp_70_fu_2080_p4;
wire   [0:0] icmp_ln46_36_fu_2096_p2;
wire   [0:0] xor_ln46_36_fu_2090_p2;
wire   [0:0] and_ln46_36_fu_2102_p2;
wire   [0:0] or_ln46_36_fu_2116_p2;
wire   [14:0] select_ln46_68_fu_2108_p3;
wire   [14:0] shl_ln46_34_fu_2072_p3;
wire   [0:0] icmp_ln45_36_fu_2054_p2;
wire   [14:0] select_ln46_36_fu_2122_p3;
wire   [7:0] trunc_ln46_37_fu_2152_p1;
wire   [0:0] tmp_71_fu_2144_p3;
wire   [10:0] tmp_72_fu_2164_p4;
wire   [0:0] icmp_ln46_37_fu_2180_p2;
wire   [0:0] xor_ln46_37_fu_2174_p2;
wire   [0:0] and_ln46_37_fu_2186_p2;
wire   [0:0] or_ln46_37_fu_2200_p2;
wire   [14:0] select_ln46_69_fu_2192_p3;
wire   [14:0] shl_ln46_35_fu_2156_p3;
wire   [0:0] icmp_ln45_37_fu_2138_p2;
wire   [14:0] select_ln46_37_fu_2206_p3;
wire   [7:0] trunc_ln46_38_fu_2236_p1;
wire   [0:0] tmp_73_fu_2228_p3;
wire   [10:0] tmp_74_fu_2248_p4;
wire   [0:0] icmp_ln46_38_fu_2264_p2;
wire   [0:0] xor_ln46_38_fu_2258_p2;
wire   [0:0] and_ln46_38_fu_2270_p2;
wire   [0:0] or_ln46_38_fu_2284_p2;
wire   [14:0] select_ln46_70_fu_2276_p3;
wire   [14:0] shl_ln46_36_fu_2240_p3;
wire   [0:0] icmp_ln45_38_fu_2222_p2;
wire   [14:0] select_ln46_38_fu_2290_p3;
wire   [7:0] trunc_ln46_39_fu_2320_p1;
wire   [0:0] tmp_75_fu_2312_p3;
wire   [10:0] tmp_76_fu_2332_p4;
wire   [0:0] icmp_ln46_39_fu_2348_p2;
wire   [0:0] xor_ln46_39_fu_2342_p2;
wire   [0:0] and_ln46_39_fu_2354_p2;
wire   [0:0] or_ln46_39_fu_2368_p2;
wire   [14:0] select_ln46_71_fu_2360_p3;
wire   [14:0] shl_ln46_37_fu_2324_p3;
wire   [0:0] icmp_ln45_39_fu_2306_p2;
wire   [14:0] select_ln46_39_fu_2374_p3;
wire   [7:0] trunc_ln46_40_fu_2404_p1;
wire   [0:0] tmp_77_fu_2396_p3;
wire   [10:0] tmp_78_fu_2416_p4;
wire   [0:0] icmp_ln46_40_fu_2432_p2;
wire   [0:0] xor_ln46_40_fu_2426_p2;
wire   [0:0] and_ln46_40_fu_2438_p2;
wire   [0:0] or_ln46_40_fu_2452_p2;
wire   [14:0] select_ln46_72_fu_2444_p3;
wire   [14:0] shl_ln46_38_fu_2408_p3;
wire   [0:0] icmp_ln45_40_fu_2390_p2;
wire   [14:0] select_ln46_40_fu_2458_p3;
wire   [7:0] trunc_ln46_41_fu_2488_p1;
wire   [0:0] tmp_79_fu_2480_p3;
wire   [10:0] tmp_80_fu_2500_p4;
wire   [0:0] icmp_ln46_41_fu_2516_p2;
wire   [0:0] xor_ln46_41_fu_2510_p2;
wire   [0:0] and_ln46_41_fu_2522_p2;
wire   [0:0] or_ln46_41_fu_2536_p2;
wire   [14:0] select_ln46_73_fu_2528_p3;
wire   [14:0] shl_ln46_39_fu_2492_p3;
wire   [0:0] icmp_ln45_41_fu_2474_p2;
wire   [14:0] select_ln46_41_fu_2542_p3;
wire   [7:0] trunc_ln46_42_fu_2572_p1;
wire   [0:0] tmp_81_fu_2564_p3;
wire   [10:0] tmp_82_fu_2584_p4;
wire   [0:0] icmp_ln46_42_fu_2600_p2;
wire   [0:0] xor_ln46_42_fu_2594_p2;
wire   [0:0] and_ln46_42_fu_2606_p2;
wire   [0:0] or_ln46_42_fu_2620_p2;
wire   [14:0] select_ln46_74_fu_2612_p3;
wire   [14:0] shl_ln46_40_fu_2576_p3;
wire   [0:0] icmp_ln45_42_fu_2558_p2;
wire   [14:0] select_ln46_42_fu_2626_p3;
wire   [7:0] trunc_ln46_43_fu_2656_p1;
wire   [0:0] tmp_83_fu_2648_p3;
wire   [10:0] tmp_84_fu_2668_p4;
wire   [0:0] icmp_ln46_43_fu_2684_p2;
wire   [0:0] xor_ln46_43_fu_2678_p2;
wire   [0:0] and_ln46_43_fu_2690_p2;
wire   [0:0] or_ln46_43_fu_2704_p2;
wire   [14:0] select_ln46_75_fu_2696_p3;
wire   [14:0] shl_ln46_41_fu_2660_p3;
wire   [0:0] icmp_ln45_43_fu_2642_p2;
wire   [14:0] select_ln46_43_fu_2710_p3;
wire   [7:0] trunc_ln46_44_fu_2740_p1;
wire   [0:0] tmp_85_fu_2732_p3;
wire   [10:0] tmp_86_fu_2752_p4;
wire   [0:0] icmp_ln46_44_fu_2768_p2;
wire   [0:0] xor_ln46_44_fu_2762_p2;
wire   [0:0] and_ln46_44_fu_2774_p2;
wire   [0:0] or_ln46_44_fu_2788_p2;
wire   [14:0] select_ln46_76_fu_2780_p3;
wire   [14:0] shl_ln46_42_fu_2744_p3;
wire   [0:0] icmp_ln45_44_fu_2726_p2;
wire   [14:0] select_ln46_44_fu_2794_p3;
wire   [7:0] trunc_ln46_45_fu_2824_p1;
wire   [0:0] tmp_87_fu_2816_p3;
wire   [10:0] tmp_88_fu_2836_p4;
wire   [0:0] icmp_ln46_45_fu_2852_p2;
wire   [0:0] xor_ln46_45_fu_2846_p2;
wire   [0:0] and_ln46_45_fu_2858_p2;
wire   [0:0] or_ln46_45_fu_2872_p2;
wire   [14:0] select_ln46_77_fu_2864_p3;
wire   [14:0] shl_ln46_43_fu_2828_p3;
wire   [0:0] icmp_ln45_45_fu_2810_p2;
wire   [14:0] select_ln46_45_fu_2878_p3;
wire   [7:0] trunc_ln46_46_fu_2908_p1;
wire   [0:0] tmp_89_fu_2900_p3;
wire   [10:0] tmp_90_fu_2920_p4;
wire   [0:0] icmp_ln46_46_fu_2936_p2;
wire   [0:0] xor_ln46_46_fu_2930_p2;
wire   [0:0] and_ln46_46_fu_2942_p2;
wire   [0:0] or_ln46_46_fu_2956_p2;
wire   [14:0] select_ln46_78_fu_2948_p3;
wire   [14:0] shl_ln46_44_fu_2912_p3;
wire   [0:0] icmp_ln45_46_fu_2894_p2;
wire   [14:0] select_ln46_46_fu_2962_p3;
wire   [14:0] res_0_0_fu_366_p3;
wire   [14:0] res_1_0_fu_450_p3;
wire   [14:0] res_2_0_fu_534_p3;
wire   [14:0] res_3_0_fu_618_p3;
wire   [14:0] res_4_0_fu_702_p3;
wire   [14:0] res_5_0_fu_786_p3;
wire   [14:0] res_6_0_fu_870_p3;
wire   [14:0] res_7_0_fu_954_p3;
wire   [14:0] res_8_0_fu_1038_p3;
wire   [14:0] res_9_0_fu_1122_p3;
wire   [14:0] res_10_0_fu_1206_p3;
wire   [14:0] res_11_0_fu_1290_p3;
wire   [14:0] res_12_0_fu_1374_p3;
wire   [14:0] res_13_0_fu_1458_p3;
wire   [14:0] res_1445_0_fu_1542_p3;
wire   [14:0] res_15_0_fu_1626_p3;
wire   [14:0] res_16_0_fu_1710_p3;
wire   [14:0] res_17_0_fu_1794_p3;
wire   [14:0] res_18_0_fu_1878_p3;
wire   [14:0] res_19_0_fu_1962_p3;
wire   [14:0] res_20_0_fu_2046_p3;
wire   [14:0] res_21_0_fu_2130_p3;
wire   [14:0] res_22_0_fu_2214_p3;
wire   [14:0] res_23_0_fu_2298_p3;
wire   [14:0] res_24_0_fu_2382_p3;
wire   [14:0] res_25_0_fu_2466_p3;
wire   [14:0] res_26_0_fu_2550_p3;
wire   [14:0] res_2786_0_fu_2634_p3;
wire   [14:0] res_28_0_fu_2718_p3;
wire   [14:0] res_29_0_fu_2802_p3;
wire   [14:0] res_30_0_fu_2886_p3;
wire   [14:0] res_31_0_fu_2970_p3;
wire    ap_ce_reg;

assign and_ln46_16_fu_422_p2 = (xor_ln46_16_fu_410_p2 & icmp_ln46_16_fu_416_p2);

assign and_ln46_17_fu_506_p2 = (xor_ln46_17_fu_494_p2 & icmp_ln46_17_fu_500_p2);

assign and_ln46_18_fu_590_p2 = (xor_ln46_18_fu_578_p2 & icmp_ln46_18_fu_584_p2);

assign and_ln46_19_fu_674_p2 = (xor_ln46_19_fu_662_p2 & icmp_ln46_19_fu_668_p2);

assign and_ln46_20_fu_758_p2 = (xor_ln46_20_fu_746_p2 & icmp_ln46_20_fu_752_p2);

assign and_ln46_21_fu_842_p2 = (xor_ln46_21_fu_830_p2 & icmp_ln46_21_fu_836_p2);

assign and_ln46_22_fu_926_p2 = (xor_ln46_22_fu_914_p2 & icmp_ln46_22_fu_920_p2);

assign and_ln46_23_fu_1010_p2 = (xor_ln46_23_fu_998_p2 & icmp_ln46_23_fu_1004_p2);

assign and_ln46_24_fu_1094_p2 = (xor_ln46_24_fu_1082_p2 & icmp_ln46_24_fu_1088_p2);

assign and_ln46_25_fu_1178_p2 = (xor_ln46_25_fu_1166_p2 & icmp_ln46_25_fu_1172_p2);

assign and_ln46_26_fu_1262_p2 = (xor_ln46_26_fu_1250_p2 & icmp_ln46_26_fu_1256_p2);

assign and_ln46_27_fu_1346_p2 = (xor_ln46_27_fu_1334_p2 & icmp_ln46_27_fu_1340_p2);

assign and_ln46_28_fu_1430_p2 = (xor_ln46_28_fu_1418_p2 & icmp_ln46_28_fu_1424_p2);

assign and_ln46_29_fu_1514_p2 = (xor_ln46_29_fu_1502_p2 & icmp_ln46_29_fu_1508_p2);

assign and_ln46_30_fu_1598_p2 = (xor_ln46_30_fu_1586_p2 & icmp_ln46_30_fu_1592_p2);

assign and_ln46_31_fu_1682_p2 = (xor_ln46_31_fu_1670_p2 & icmp_ln46_31_fu_1676_p2);

assign and_ln46_32_fu_1766_p2 = (xor_ln46_32_fu_1754_p2 & icmp_ln46_32_fu_1760_p2);

assign and_ln46_33_fu_1850_p2 = (xor_ln46_33_fu_1838_p2 & icmp_ln46_33_fu_1844_p2);

assign and_ln46_34_fu_1934_p2 = (xor_ln46_34_fu_1922_p2 & icmp_ln46_34_fu_1928_p2);

assign and_ln46_35_fu_2018_p2 = (xor_ln46_35_fu_2006_p2 & icmp_ln46_35_fu_2012_p2);

assign and_ln46_36_fu_2102_p2 = (xor_ln46_36_fu_2090_p2 & icmp_ln46_36_fu_2096_p2);

assign and_ln46_37_fu_2186_p2 = (xor_ln46_37_fu_2174_p2 & icmp_ln46_37_fu_2180_p2);

assign and_ln46_38_fu_2270_p2 = (xor_ln46_38_fu_2258_p2 & icmp_ln46_38_fu_2264_p2);

assign and_ln46_39_fu_2354_p2 = (xor_ln46_39_fu_2342_p2 & icmp_ln46_39_fu_2348_p2);

assign and_ln46_40_fu_2438_p2 = (xor_ln46_40_fu_2426_p2 & icmp_ln46_40_fu_2432_p2);

assign and_ln46_41_fu_2522_p2 = (xor_ln46_41_fu_2510_p2 & icmp_ln46_41_fu_2516_p2);

assign and_ln46_42_fu_2606_p2 = (xor_ln46_42_fu_2594_p2 & icmp_ln46_42_fu_2600_p2);

assign and_ln46_43_fu_2690_p2 = (xor_ln46_43_fu_2678_p2 & icmp_ln46_43_fu_2684_p2);

assign and_ln46_44_fu_2774_p2 = (xor_ln46_44_fu_2762_p2 & icmp_ln46_44_fu_2768_p2);

assign and_ln46_45_fu_2858_p2 = (xor_ln46_45_fu_2846_p2 & icmp_ln46_45_fu_2852_p2);

assign and_ln46_46_fu_2942_p2 = (xor_ln46_46_fu_2930_p2 & icmp_ln46_46_fu_2936_p2);

assign and_ln46_fu_338_p2 = (xor_ln46_fu_326_p2 & icmp_ln46_fu_332_p2);

assign ap_ready = 1'b1;

assign icmp_ln46_16_fu_416_p2 = ((tmp_s_fu_400_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_17_fu_500_p2 = ((tmp_32_fu_484_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_18_fu_584_p2 = ((tmp_34_fu_568_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_19_fu_668_p2 = ((tmp_36_fu_652_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_20_fu_752_p2 = ((tmp_38_fu_736_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_21_fu_836_p2 = ((tmp_40_fu_820_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_22_fu_920_p2 = ((tmp_42_fu_904_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_23_fu_1004_p2 = ((tmp_44_fu_988_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_24_fu_1088_p2 = ((tmp_46_fu_1072_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_25_fu_1172_p2 = ((tmp_48_fu_1156_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_26_fu_1256_p2 = ((tmp_50_fu_1240_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_27_fu_1340_p2 = ((tmp_52_fu_1324_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_28_fu_1424_p2 = ((tmp_54_fu_1408_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_29_fu_1508_p2 = ((tmp_56_fu_1492_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_30_fu_1592_p2 = ((tmp_58_fu_1576_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_31_fu_1676_p2 = ((tmp_60_fu_1660_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_32_fu_1760_p2 = ((tmp_62_fu_1744_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_33_fu_1844_p2 = ((tmp_64_fu_1828_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_34_fu_1928_p2 = ((tmp_66_fu_1912_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_35_fu_2012_p2 = ((tmp_68_fu_1996_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_36_fu_2096_p2 = ((tmp_70_fu_2080_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_37_fu_2180_p2 = ((tmp_72_fu_2164_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_38_fu_2264_p2 = ((tmp_74_fu_2248_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_39_fu_2348_p2 = ((tmp_76_fu_2332_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_40_fu_2432_p2 = ((tmp_78_fu_2416_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_41_fu_2516_p2 = ((tmp_80_fu_2500_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_42_fu_2600_p2 = ((tmp_82_fu_2584_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_43_fu_2684_p2 = ((tmp_84_fu_2668_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_44_fu_2768_p2 = ((tmp_86_fu_2752_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_45_fu_2852_p2 = ((tmp_88_fu_2836_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_46_fu_2936_p2 = ((tmp_90_fu_2920_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_332_p2 = ((tmp_1_fu_316_p4 != 11'd0) ? 1'b1 : 1'b0);

assign or_ln46_16_fu_436_p2 = (tmp_30_fu_380_p3 | and_ln46_16_fu_422_p2);

assign or_ln46_17_fu_520_p2 = (tmp_31_fu_464_p3 | and_ln46_17_fu_506_p2);

assign or_ln46_18_fu_604_p2 = (tmp_33_fu_548_p3 | and_ln46_18_fu_590_p2);

assign or_ln46_19_fu_688_p2 = (tmp_35_fu_632_p3 | and_ln46_19_fu_674_p2);

assign or_ln46_20_fu_772_p2 = (tmp_37_fu_716_p3 | and_ln46_20_fu_758_p2);

assign or_ln46_21_fu_856_p2 = (tmp_39_fu_800_p3 | and_ln46_21_fu_842_p2);

assign or_ln46_22_fu_940_p2 = (tmp_41_fu_884_p3 | and_ln46_22_fu_926_p2);

assign or_ln46_23_fu_1024_p2 = (tmp_43_fu_968_p3 | and_ln46_23_fu_1010_p2);

assign or_ln46_24_fu_1108_p2 = (tmp_45_fu_1052_p3 | and_ln46_24_fu_1094_p2);

assign or_ln46_25_fu_1192_p2 = (tmp_47_fu_1136_p3 | and_ln46_25_fu_1178_p2);

assign or_ln46_26_fu_1276_p2 = (tmp_49_fu_1220_p3 | and_ln46_26_fu_1262_p2);

assign or_ln46_27_fu_1360_p2 = (tmp_51_fu_1304_p3 | and_ln46_27_fu_1346_p2);

assign or_ln46_28_fu_1444_p2 = (tmp_53_fu_1388_p3 | and_ln46_28_fu_1430_p2);

assign or_ln46_29_fu_1528_p2 = (tmp_55_fu_1472_p3 | and_ln46_29_fu_1514_p2);

assign or_ln46_30_fu_1612_p2 = (tmp_57_fu_1556_p3 | and_ln46_30_fu_1598_p2);

assign or_ln46_31_fu_1696_p2 = (tmp_59_fu_1640_p3 | and_ln46_31_fu_1682_p2);

assign or_ln46_32_fu_1780_p2 = (tmp_61_fu_1724_p3 | and_ln46_32_fu_1766_p2);

assign or_ln46_33_fu_1864_p2 = (tmp_63_fu_1808_p3 | and_ln46_33_fu_1850_p2);

assign or_ln46_34_fu_1948_p2 = (tmp_65_fu_1892_p3 | and_ln46_34_fu_1934_p2);

assign or_ln46_35_fu_2032_p2 = (tmp_67_fu_1976_p3 | and_ln46_35_fu_2018_p2);

assign or_ln46_36_fu_2116_p2 = (tmp_69_fu_2060_p3 | and_ln46_36_fu_2102_p2);

assign or_ln46_37_fu_2200_p2 = (tmp_71_fu_2144_p3 | and_ln46_37_fu_2186_p2);

assign or_ln46_38_fu_2284_p2 = (tmp_73_fu_2228_p3 | and_ln46_38_fu_2270_p2);

assign or_ln46_39_fu_2368_p2 = (tmp_75_fu_2312_p3 | and_ln46_39_fu_2354_p2);

assign or_ln46_40_fu_2452_p2 = (tmp_77_fu_2396_p3 | and_ln46_40_fu_2438_p2);

assign or_ln46_41_fu_2536_p2 = (tmp_79_fu_2480_p3 | and_ln46_41_fu_2522_p2);

assign or_ln46_42_fu_2620_p2 = (tmp_81_fu_2564_p3 | and_ln46_42_fu_2606_p2);

assign or_ln46_43_fu_2704_p2 = (tmp_83_fu_2648_p3 | and_ln46_43_fu_2690_p2);

assign or_ln46_44_fu_2788_p2 = (tmp_85_fu_2732_p3 | and_ln46_44_fu_2774_p2);

assign or_ln46_45_fu_2872_p2 = (tmp_87_fu_2816_p3 | and_ln46_45_fu_2858_p2);

assign or_ln46_46_fu_2956_p2 = (tmp_89_fu_2900_p3 | and_ln46_46_fu_2942_p2);

assign or_ln46_fu_352_p2 = (tmp_fu_296_p3 | and_ln46_fu_338_p2);

assign res_0_0_fu_366_p3 = ((icmp_ln45_fu_290_p2[0:0] == 1'b1) ? select_ln46_fu_358_p3 : 15'd0);

assign res_10_0_fu_1206_p3 = ((icmp_ln45_25_fu_1130_p2[0:0] == 1'b1) ? select_ln46_25_fu_1198_p3 : 15'd0);

assign res_11_0_fu_1290_p3 = ((icmp_ln45_26_fu_1214_p2[0:0] == 1'b1) ? select_ln46_26_fu_1282_p3 : 15'd0);

assign res_12_0_fu_1374_p3 = ((icmp_ln45_27_fu_1298_p2[0:0] == 1'b1) ? select_ln46_27_fu_1366_p3 : 15'd0);

assign res_13_0_fu_1458_p3 = ((icmp_ln45_28_fu_1382_p2[0:0] == 1'b1) ? select_ln46_28_fu_1450_p3 : 15'd0);

assign res_1445_0_fu_1542_p3 = ((icmp_ln45_29_fu_1466_p2[0:0] == 1'b1) ? select_ln46_29_fu_1534_p3 : 15'd0);

assign res_15_0_fu_1626_p3 = ((icmp_ln45_30_fu_1550_p2[0:0] == 1'b1) ? select_ln46_30_fu_1618_p3 : 15'd0);

assign res_16_0_fu_1710_p3 = ((icmp_ln45_31_fu_1634_p2[0:0] == 1'b1) ? select_ln46_31_fu_1702_p3 : 15'd0);

assign res_17_0_fu_1794_p3 = ((icmp_ln45_32_fu_1718_p2[0:0] == 1'b1) ? select_ln46_32_fu_1786_p3 : 15'd0);

assign res_18_0_fu_1878_p3 = ((icmp_ln45_33_fu_1802_p2[0:0] == 1'b1) ? select_ln46_33_fu_1870_p3 : 15'd0);

assign res_19_0_fu_1962_p3 = ((icmp_ln45_34_fu_1886_p2[0:0] == 1'b1) ? select_ln46_34_fu_1954_p3 : 15'd0);

assign res_1_0_fu_450_p3 = ((icmp_ln45_16_fu_374_p2[0:0] == 1'b1) ? select_ln46_16_fu_442_p3 : 15'd0);

assign res_20_0_fu_2046_p3 = ((icmp_ln45_35_fu_1970_p2[0:0] == 1'b1) ? select_ln46_35_fu_2038_p3 : 15'd0);

assign res_21_0_fu_2130_p3 = ((icmp_ln45_36_fu_2054_p2[0:0] == 1'b1) ? select_ln46_36_fu_2122_p3 : 15'd0);

assign res_22_0_fu_2214_p3 = ((icmp_ln45_37_fu_2138_p2[0:0] == 1'b1) ? select_ln46_37_fu_2206_p3 : 15'd0);

assign res_23_0_fu_2298_p3 = ((icmp_ln45_38_fu_2222_p2[0:0] == 1'b1) ? select_ln46_38_fu_2290_p3 : 15'd0);

assign res_24_0_fu_2382_p3 = ((icmp_ln45_39_fu_2306_p2[0:0] == 1'b1) ? select_ln46_39_fu_2374_p3 : 15'd0);

assign res_25_0_fu_2466_p3 = ((icmp_ln45_40_fu_2390_p2[0:0] == 1'b1) ? select_ln46_40_fu_2458_p3 : 15'd0);

assign res_26_0_fu_2550_p3 = ((icmp_ln45_41_fu_2474_p2[0:0] == 1'b1) ? select_ln46_41_fu_2542_p3 : 15'd0);

assign res_2786_0_fu_2634_p3 = ((icmp_ln45_42_fu_2558_p2[0:0] == 1'b1) ? select_ln46_42_fu_2626_p3 : 15'd0);

assign res_28_0_fu_2718_p3 = ((icmp_ln45_43_fu_2642_p2[0:0] == 1'b1) ? select_ln46_43_fu_2710_p3 : 15'd0);

assign res_29_0_fu_2802_p3 = ((icmp_ln45_44_fu_2726_p2[0:0] == 1'b1) ? select_ln46_44_fu_2794_p3 : 15'd0);

assign res_2_0_fu_534_p3 = ((icmp_ln45_17_fu_458_p2[0:0] == 1'b1) ? select_ln46_17_fu_526_p3 : 15'd0);

assign res_30_0_fu_2886_p3 = ((icmp_ln45_45_fu_2810_p2[0:0] == 1'b1) ? select_ln46_45_fu_2878_p3 : 15'd0);

assign res_31_0_fu_2970_p3 = ((icmp_ln45_46_fu_2894_p2[0:0] == 1'b1) ? select_ln46_46_fu_2962_p3 : 15'd0);

assign res_3_0_fu_618_p3 = ((icmp_ln45_18_fu_542_p2[0:0] == 1'b1) ? select_ln46_18_fu_610_p3 : 15'd0);

assign res_4_0_fu_702_p3 = ((icmp_ln45_19_fu_626_p2[0:0] == 1'b1) ? select_ln46_19_fu_694_p3 : 15'd0);

assign res_5_0_fu_786_p3 = ((icmp_ln45_20_fu_710_p2[0:0] == 1'b1) ? select_ln46_20_fu_778_p3 : 15'd0);

assign res_6_0_fu_870_p3 = ((icmp_ln45_21_fu_794_p2[0:0] == 1'b1) ? select_ln46_21_fu_862_p3 : 15'd0);

assign res_7_0_fu_954_p3 = ((icmp_ln45_22_fu_878_p2[0:0] == 1'b1) ? select_ln46_22_fu_946_p3 : 15'd0);

assign res_8_0_fu_1038_p3 = ((icmp_ln45_23_fu_962_p2[0:0] == 1'b1) ? select_ln46_23_fu_1030_p3 : 15'd0);

assign res_9_0_fu_1122_p3 = ((icmp_ln45_24_fu_1046_p2[0:0] == 1'b1) ? select_ln46_24_fu_1114_p3 : 15'd0);

assign select_ln46_16_fu_442_p3 = ((or_ln46_16_fu_436_p2[0:0] == 1'b1) ? select_ln46_48_fu_428_p3 : shl_ln46_s_fu_392_p3);

assign select_ln46_17_fu_526_p3 = ((or_ln46_17_fu_520_p2[0:0] == 1'b1) ? select_ln46_49_fu_512_p3 : shl_ln46_15_fu_476_p3);

assign select_ln46_18_fu_610_p3 = ((or_ln46_18_fu_604_p2[0:0] == 1'b1) ? select_ln46_50_fu_596_p3 : shl_ln46_16_fu_560_p3);

assign select_ln46_19_fu_694_p3 = ((or_ln46_19_fu_688_p2[0:0] == 1'b1) ? select_ln46_51_fu_680_p3 : shl_ln46_17_fu_644_p3);

assign select_ln46_20_fu_778_p3 = ((or_ln46_20_fu_772_p2[0:0] == 1'b1) ? select_ln46_52_fu_764_p3 : shl_ln46_18_fu_728_p3);

assign select_ln46_21_fu_862_p3 = ((or_ln46_21_fu_856_p2[0:0] == 1'b1) ? select_ln46_53_fu_848_p3 : shl_ln46_19_fu_812_p3);

assign select_ln46_22_fu_946_p3 = ((or_ln46_22_fu_940_p2[0:0] == 1'b1) ? select_ln46_54_fu_932_p3 : shl_ln46_20_fu_896_p3);

assign select_ln46_23_fu_1030_p3 = ((or_ln46_23_fu_1024_p2[0:0] == 1'b1) ? select_ln46_55_fu_1016_p3 : shl_ln46_21_fu_980_p3);

assign select_ln46_24_fu_1114_p3 = ((or_ln46_24_fu_1108_p2[0:0] == 1'b1) ? select_ln46_56_fu_1100_p3 : shl_ln46_22_fu_1064_p3);

assign select_ln46_25_fu_1198_p3 = ((or_ln46_25_fu_1192_p2[0:0] == 1'b1) ? select_ln46_57_fu_1184_p3 : shl_ln46_23_fu_1148_p3);

assign select_ln46_26_fu_1282_p3 = ((or_ln46_26_fu_1276_p2[0:0] == 1'b1) ? select_ln46_58_fu_1268_p3 : shl_ln46_24_fu_1232_p3);

assign select_ln46_27_fu_1366_p3 = ((or_ln46_27_fu_1360_p2[0:0] == 1'b1) ? select_ln46_59_fu_1352_p3 : shl_ln46_25_fu_1316_p3);

assign select_ln46_28_fu_1450_p3 = ((or_ln46_28_fu_1444_p2[0:0] == 1'b1) ? select_ln46_60_fu_1436_p3 : shl_ln46_26_fu_1400_p3);

assign select_ln46_29_fu_1534_p3 = ((or_ln46_29_fu_1528_p2[0:0] == 1'b1) ? select_ln46_61_fu_1520_p3 : shl_ln46_27_fu_1484_p3);

assign select_ln46_30_fu_1618_p3 = ((or_ln46_30_fu_1612_p2[0:0] == 1'b1) ? select_ln46_62_fu_1604_p3 : shl_ln46_28_fu_1568_p3);

assign select_ln46_31_fu_1702_p3 = ((or_ln46_31_fu_1696_p2[0:0] == 1'b1) ? select_ln46_63_fu_1688_p3 : shl_ln46_29_fu_1652_p3);

assign select_ln46_32_fu_1786_p3 = ((or_ln46_32_fu_1780_p2[0:0] == 1'b1) ? select_ln46_64_fu_1772_p3 : shl_ln46_30_fu_1736_p3);

assign select_ln46_33_fu_1870_p3 = ((or_ln46_33_fu_1864_p2[0:0] == 1'b1) ? select_ln46_65_fu_1856_p3 : shl_ln46_31_fu_1820_p3);

assign select_ln46_34_fu_1954_p3 = ((or_ln46_34_fu_1948_p2[0:0] == 1'b1) ? select_ln46_66_fu_1940_p3 : shl_ln46_32_fu_1904_p3);

assign select_ln46_35_fu_2038_p3 = ((or_ln46_35_fu_2032_p2[0:0] == 1'b1) ? select_ln46_67_fu_2024_p3 : shl_ln46_33_fu_1988_p3);

assign select_ln46_36_fu_2122_p3 = ((or_ln46_36_fu_2116_p2[0:0] == 1'b1) ? select_ln46_68_fu_2108_p3 : shl_ln46_34_fu_2072_p3);

assign select_ln46_37_fu_2206_p3 = ((or_ln46_37_fu_2200_p2[0:0] == 1'b1) ? select_ln46_69_fu_2192_p3 : shl_ln46_35_fu_2156_p3);

assign select_ln46_38_fu_2290_p3 = ((or_ln46_38_fu_2284_p2[0:0] == 1'b1) ? select_ln46_70_fu_2276_p3 : shl_ln46_36_fu_2240_p3);

assign select_ln46_39_fu_2374_p3 = ((or_ln46_39_fu_2368_p2[0:0] == 1'b1) ? select_ln46_71_fu_2360_p3 : shl_ln46_37_fu_2324_p3);

assign select_ln46_40_fu_2458_p3 = ((or_ln46_40_fu_2452_p2[0:0] == 1'b1) ? select_ln46_72_fu_2444_p3 : shl_ln46_38_fu_2408_p3);

assign select_ln46_41_fu_2542_p3 = ((or_ln46_41_fu_2536_p2[0:0] == 1'b1) ? select_ln46_73_fu_2528_p3 : shl_ln46_39_fu_2492_p3);

assign select_ln46_42_fu_2626_p3 = ((or_ln46_42_fu_2620_p2[0:0] == 1'b1) ? select_ln46_74_fu_2612_p3 : shl_ln46_40_fu_2576_p3);

assign select_ln46_43_fu_2710_p3 = ((or_ln46_43_fu_2704_p2[0:0] == 1'b1) ? select_ln46_75_fu_2696_p3 : shl_ln46_41_fu_2660_p3);

assign select_ln46_44_fu_2794_p3 = ((or_ln46_44_fu_2788_p2[0:0] == 1'b1) ? select_ln46_76_fu_2780_p3 : shl_ln46_42_fu_2744_p3);

assign select_ln46_45_fu_2878_p3 = ((or_ln46_45_fu_2872_p2[0:0] == 1'b1) ? select_ln46_77_fu_2864_p3 : shl_ln46_43_fu_2828_p3);

assign select_ln46_46_fu_2962_p3 = ((or_ln46_46_fu_2956_p2[0:0] == 1'b1) ? select_ln46_78_fu_2948_p3 : shl_ln46_44_fu_2912_p3);

assign select_ln46_47_fu_344_p3 = ((and_ln46_fu_338_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_48_fu_428_p3 = ((and_ln46_16_fu_422_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_49_fu_512_p3 = ((and_ln46_17_fu_506_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_50_fu_596_p3 = ((and_ln46_18_fu_590_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_51_fu_680_p3 = ((and_ln46_19_fu_674_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_52_fu_764_p3 = ((and_ln46_20_fu_758_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_53_fu_848_p3 = ((and_ln46_21_fu_842_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_54_fu_932_p3 = ((and_ln46_22_fu_926_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_55_fu_1016_p3 = ((and_ln46_23_fu_1010_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_56_fu_1100_p3 = ((and_ln46_24_fu_1094_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_57_fu_1184_p3 = ((and_ln46_25_fu_1178_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_58_fu_1268_p3 = ((and_ln46_26_fu_1262_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_59_fu_1352_p3 = ((and_ln46_27_fu_1346_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_60_fu_1436_p3 = ((and_ln46_28_fu_1430_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_61_fu_1520_p3 = ((and_ln46_29_fu_1514_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_62_fu_1604_p3 = ((and_ln46_30_fu_1598_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_63_fu_1688_p3 = ((and_ln46_31_fu_1682_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_64_fu_1772_p3 = ((and_ln46_32_fu_1766_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_65_fu_1856_p3 = ((and_ln46_33_fu_1850_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_66_fu_1940_p3 = ((and_ln46_34_fu_1934_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_67_fu_2024_p3 = ((and_ln46_35_fu_2018_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_68_fu_2108_p3 = ((and_ln46_36_fu_2102_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_69_fu_2192_p3 = ((and_ln46_37_fu_2186_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_70_fu_2276_p3 = ((and_ln46_38_fu_2270_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_71_fu_2360_p3 = ((and_ln46_39_fu_2354_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_72_fu_2444_p3 = ((and_ln46_40_fu_2438_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_73_fu_2528_p3 = ((and_ln46_41_fu_2522_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_74_fu_2612_p3 = ((and_ln46_42_fu_2606_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_75_fu_2696_p3 = ((and_ln46_43_fu_2690_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_76_fu_2780_p3 = ((and_ln46_44_fu_2774_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_77_fu_2864_p3 = ((and_ln46_45_fu_2858_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_78_fu_2948_p3 = ((and_ln46_46_fu_2942_p2[0:0] == 1'b1) ? 15'd32767 : 15'd0);

assign select_ln46_fu_358_p3 = ((or_ln46_fu_352_p2[0:0] == 1'b1) ? select_ln46_47_fu_344_p3 : shl_ln_fu_308_p3);

assign shl_ln46_15_fu_476_p3 = {{trunc_ln46_17_fu_472_p1}, {7'd0}};

assign shl_ln46_16_fu_560_p3 = {{trunc_ln46_18_fu_556_p1}, {7'd0}};

assign shl_ln46_17_fu_644_p3 = {{trunc_ln46_19_fu_640_p1}, {7'd0}};

assign shl_ln46_18_fu_728_p3 = {{trunc_ln46_20_fu_724_p1}, {7'd0}};

assign shl_ln46_19_fu_812_p3 = {{trunc_ln46_21_fu_808_p1}, {7'd0}};

assign shl_ln46_20_fu_896_p3 = {{trunc_ln46_22_fu_892_p1}, {7'd0}};

assign shl_ln46_21_fu_980_p3 = {{trunc_ln46_23_fu_976_p1}, {7'd0}};

assign shl_ln46_22_fu_1064_p3 = {{trunc_ln46_24_fu_1060_p1}, {7'd0}};

assign shl_ln46_23_fu_1148_p3 = {{trunc_ln46_25_fu_1144_p1}, {7'd0}};

assign shl_ln46_24_fu_1232_p3 = {{trunc_ln46_26_fu_1228_p1}, {7'd0}};

assign shl_ln46_25_fu_1316_p3 = {{trunc_ln46_27_fu_1312_p1}, {7'd0}};

assign shl_ln46_26_fu_1400_p3 = {{trunc_ln46_28_fu_1396_p1}, {7'd0}};

assign shl_ln46_27_fu_1484_p3 = {{trunc_ln46_29_fu_1480_p1}, {7'd0}};

assign shl_ln46_28_fu_1568_p3 = {{trunc_ln46_30_fu_1564_p1}, {7'd0}};

assign shl_ln46_29_fu_1652_p3 = {{trunc_ln46_31_fu_1648_p1}, {7'd0}};

assign shl_ln46_30_fu_1736_p3 = {{trunc_ln46_32_fu_1732_p1}, {7'd0}};

assign shl_ln46_31_fu_1820_p3 = {{trunc_ln46_33_fu_1816_p1}, {7'd0}};

assign shl_ln46_32_fu_1904_p3 = {{trunc_ln46_34_fu_1900_p1}, {7'd0}};

assign shl_ln46_33_fu_1988_p3 = {{trunc_ln46_35_fu_1984_p1}, {7'd0}};

assign shl_ln46_34_fu_2072_p3 = {{trunc_ln46_36_fu_2068_p1}, {7'd0}};

assign shl_ln46_35_fu_2156_p3 = {{trunc_ln46_37_fu_2152_p1}, {7'd0}};

assign shl_ln46_36_fu_2240_p3 = {{trunc_ln46_38_fu_2236_p1}, {7'd0}};

assign shl_ln46_37_fu_2324_p3 = {{trunc_ln46_39_fu_2320_p1}, {7'd0}};

assign shl_ln46_38_fu_2408_p3 = {{trunc_ln46_40_fu_2404_p1}, {7'd0}};

assign shl_ln46_39_fu_2492_p3 = {{trunc_ln46_41_fu_2488_p1}, {7'd0}};

assign shl_ln46_40_fu_2576_p3 = {{trunc_ln46_42_fu_2572_p1}, {7'd0}};

assign shl_ln46_41_fu_2660_p3 = {{trunc_ln46_43_fu_2656_p1}, {7'd0}};

assign shl_ln46_42_fu_2744_p3 = {{trunc_ln46_44_fu_2740_p1}, {7'd0}};

assign shl_ln46_43_fu_2828_p3 = {{trunc_ln46_45_fu_2824_p1}, {7'd0}};

assign shl_ln46_44_fu_2912_p3 = {{trunc_ln46_46_fu_2908_p1}, {7'd0}};

assign shl_ln46_s_fu_392_p3 = {{trunc_ln46_16_fu_388_p1}, {7'd0}};

assign shl_ln_fu_308_p3 = {{trunc_ln46_fu_304_p1}, {7'd0}};

assign tmp_1_fu_316_p4 = {{data_0_val[18:8]}};

assign tmp_30_fu_380_p3 = data_1_val[32'd18];

assign tmp_31_fu_464_p3 = data_2_val[32'd18];

assign tmp_32_fu_484_p4 = {{data_2_val[18:8]}};

assign tmp_33_fu_548_p3 = data_3_val[32'd18];

assign tmp_34_fu_568_p4 = {{data_3_val[18:8]}};

assign tmp_35_fu_632_p3 = data_4_val[32'd18];

assign tmp_36_fu_652_p4 = {{data_4_val[18:8]}};

assign tmp_37_fu_716_p3 = data_5_val[32'd18];

assign tmp_38_fu_736_p4 = {{data_5_val[18:8]}};

assign tmp_39_fu_800_p3 = data_6_val[32'd18];

assign tmp_40_fu_820_p4 = {{data_6_val[18:8]}};

assign tmp_41_fu_884_p3 = data_7_val[32'd18];

assign tmp_42_fu_904_p4 = {{data_7_val[18:8]}};

assign tmp_43_fu_968_p3 = data_8_val[32'd18];

assign tmp_44_fu_988_p4 = {{data_8_val[18:8]}};

assign tmp_45_fu_1052_p3 = data_9_val[32'd18];

assign tmp_46_fu_1072_p4 = {{data_9_val[18:8]}};

assign tmp_47_fu_1136_p3 = data_10_val[32'd18];

assign tmp_48_fu_1156_p4 = {{data_10_val[18:8]}};

assign tmp_49_fu_1220_p3 = data_11_val[32'd18];

assign tmp_50_fu_1240_p4 = {{data_11_val[18:8]}};

assign tmp_51_fu_1304_p3 = data_12_val[32'd18];

assign tmp_52_fu_1324_p4 = {{data_12_val[18:8]}};

assign tmp_53_fu_1388_p3 = data_13_val[32'd18];

assign tmp_54_fu_1408_p4 = {{data_13_val[18:8]}};

assign tmp_55_fu_1472_p3 = data_14_val[32'd18];

assign tmp_56_fu_1492_p4 = {{data_14_val[18:8]}};

assign tmp_57_fu_1556_p3 = data_15_val[32'd18];

assign tmp_58_fu_1576_p4 = {{data_15_val[18:8]}};

assign tmp_59_fu_1640_p3 = data_16_val[32'd18];

assign tmp_60_fu_1660_p4 = {{data_16_val[18:8]}};

assign tmp_61_fu_1724_p3 = data_17_val[32'd18];

assign tmp_62_fu_1744_p4 = {{data_17_val[18:8]}};

assign tmp_63_fu_1808_p3 = data_18_val[32'd18];

assign tmp_64_fu_1828_p4 = {{data_18_val[18:8]}};

assign tmp_65_fu_1892_p3 = data_19_val[32'd18];

assign tmp_66_fu_1912_p4 = {{data_19_val[18:8]}};

assign tmp_67_fu_1976_p3 = data_20_val[32'd18];

assign tmp_68_fu_1996_p4 = {{data_20_val[18:8]}};

assign tmp_69_fu_2060_p3 = data_21_val[32'd18];

assign tmp_70_fu_2080_p4 = {{data_21_val[18:8]}};

assign tmp_71_fu_2144_p3 = data_22_val[32'd18];

assign tmp_72_fu_2164_p4 = {{data_22_val[18:8]}};

assign tmp_73_fu_2228_p3 = data_23_val[32'd18];

assign tmp_74_fu_2248_p4 = {{data_23_val[18:8]}};

assign tmp_75_fu_2312_p3 = data_24_val[32'd18];

assign tmp_76_fu_2332_p4 = {{data_24_val[18:8]}};

assign tmp_77_fu_2396_p3 = data_25_val[32'd18];

assign tmp_78_fu_2416_p4 = {{data_25_val[18:8]}};

assign tmp_79_fu_2480_p3 = data_26_val[32'd18];

assign tmp_80_fu_2500_p4 = {{data_26_val[18:8]}};

assign tmp_81_fu_2564_p3 = data_27_val[32'd18];

assign tmp_82_fu_2584_p4 = {{data_27_val[18:8]}};

assign tmp_83_fu_2648_p3 = data_28_val[32'd18];

assign tmp_84_fu_2668_p4 = {{data_28_val[18:8]}};

assign tmp_85_fu_2732_p3 = data_29_val[32'd18];

assign tmp_86_fu_2752_p4 = {{data_29_val[18:8]}};

assign tmp_87_fu_2816_p3 = data_30_val[32'd18];

assign tmp_88_fu_2836_p4 = {{data_30_val[18:8]}};

assign tmp_89_fu_2900_p3 = data_31_val[32'd18];

assign tmp_90_fu_2920_p4 = {{data_31_val[18:8]}};

assign tmp_fu_296_p3 = data_0_val[32'd18];

assign tmp_s_fu_400_p4 = {{data_1_val[18:8]}};

assign trunc_ln46_16_fu_388_p1 = data_1_val[7:0];

assign trunc_ln46_17_fu_472_p1 = data_2_val[7:0];

assign trunc_ln46_18_fu_556_p1 = data_3_val[7:0];

assign trunc_ln46_19_fu_640_p1 = data_4_val[7:0];

assign trunc_ln46_20_fu_724_p1 = data_5_val[7:0];

assign trunc_ln46_21_fu_808_p1 = data_6_val[7:0];

assign trunc_ln46_22_fu_892_p1 = data_7_val[7:0];

assign trunc_ln46_23_fu_976_p1 = data_8_val[7:0];

assign trunc_ln46_24_fu_1060_p1 = data_9_val[7:0];

assign trunc_ln46_25_fu_1144_p1 = data_10_val[7:0];

assign trunc_ln46_26_fu_1228_p1 = data_11_val[7:0];

assign trunc_ln46_27_fu_1312_p1 = data_12_val[7:0];

assign trunc_ln46_28_fu_1396_p1 = data_13_val[7:0];

assign trunc_ln46_29_fu_1480_p1 = data_14_val[7:0];

assign trunc_ln46_30_fu_1564_p1 = data_15_val[7:0];

assign trunc_ln46_31_fu_1648_p1 = data_16_val[7:0];

assign trunc_ln46_32_fu_1732_p1 = data_17_val[7:0];

assign trunc_ln46_33_fu_1816_p1 = data_18_val[7:0];

assign trunc_ln46_34_fu_1900_p1 = data_19_val[7:0];

assign trunc_ln46_35_fu_1984_p1 = data_20_val[7:0];

assign trunc_ln46_36_fu_2068_p1 = data_21_val[7:0];

assign trunc_ln46_37_fu_2152_p1 = data_22_val[7:0];

assign trunc_ln46_38_fu_2236_p1 = data_23_val[7:0];

assign trunc_ln46_39_fu_2320_p1 = data_24_val[7:0];

assign trunc_ln46_40_fu_2404_p1 = data_25_val[7:0];

assign trunc_ln46_41_fu_2488_p1 = data_26_val[7:0];

assign trunc_ln46_42_fu_2572_p1 = data_27_val[7:0];

assign trunc_ln46_43_fu_2656_p1 = data_28_val[7:0];

assign trunc_ln46_44_fu_2740_p1 = data_29_val[7:0];

assign trunc_ln46_45_fu_2824_p1 = data_30_val[7:0];

assign trunc_ln46_46_fu_2908_p1 = data_31_val[7:0];

assign trunc_ln46_fu_304_p1 = data_0_val[7:0];

assign xor_ln46_16_fu_410_p2 = (tmp_30_fu_380_p3 ^ 1'd1);

assign xor_ln46_17_fu_494_p2 = (tmp_31_fu_464_p3 ^ 1'd1);

assign xor_ln46_18_fu_578_p2 = (tmp_33_fu_548_p3 ^ 1'd1);

assign xor_ln46_19_fu_662_p2 = (tmp_35_fu_632_p3 ^ 1'd1);

assign xor_ln46_20_fu_746_p2 = (tmp_37_fu_716_p3 ^ 1'd1);

assign xor_ln46_21_fu_830_p2 = (tmp_39_fu_800_p3 ^ 1'd1);

assign xor_ln46_22_fu_914_p2 = (tmp_41_fu_884_p3 ^ 1'd1);

assign xor_ln46_23_fu_998_p2 = (tmp_43_fu_968_p3 ^ 1'd1);

assign xor_ln46_24_fu_1082_p2 = (tmp_45_fu_1052_p3 ^ 1'd1);

assign xor_ln46_25_fu_1166_p2 = (tmp_47_fu_1136_p3 ^ 1'd1);

assign xor_ln46_26_fu_1250_p2 = (tmp_49_fu_1220_p3 ^ 1'd1);

assign xor_ln46_27_fu_1334_p2 = (tmp_51_fu_1304_p3 ^ 1'd1);

assign xor_ln46_28_fu_1418_p2 = (tmp_53_fu_1388_p3 ^ 1'd1);

assign xor_ln46_29_fu_1502_p2 = (tmp_55_fu_1472_p3 ^ 1'd1);

assign xor_ln46_30_fu_1586_p2 = (tmp_57_fu_1556_p3 ^ 1'd1);

assign xor_ln46_31_fu_1670_p2 = (tmp_59_fu_1640_p3 ^ 1'd1);

assign xor_ln46_32_fu_1754_p2 = (tmp_61_fu_1724_p3 ^ 1'd1);

assign xor_ln46_33_fu_1838_p2 = (tmp_63_fu_1808_p3 ^ 1'd1);

assign xor_ln46_34_fu_1922_p2 = (tmp_65_fu_1892_p3 ^ 1'd1);

assign xor_ln46_35_fu_2006_p2 = (tmp_67_fu_1976_p3 ^ 1'd1);

assign xor_ln46_36_fu_2090_p2 = (tmp_69_fu_2060_p3 ^ 1'd1);

assign xor_ln46_37_fu_2174_p2 = (tmp_71_fu_2144_p3 ^ 1'd1);

assign xor_ln46_38_fu_2258_p2 = (tmp_73_fu_2228_p3 ^ 1'd1);

assign xor_ln46_39_fu_2342_p2 = (tmp_75_fu_2312_p3 ^ 1'd1);

assign xor_ln46_40_fu_2426_p2 = (tmp_77_fu_2396_p3 ^ 1'd1);

assign xor_ln46_41_fu_2510_p2 = (tmp_79_fu_2480_p3 ^ 1'd1);

assign xor_ln46_42_fu_2594_p2 = (tmp_81_fu_2564_p3 ^ 1'd1);

assign xor_ln46_43_fu_2678_p2 = (tmp_83_fu_2648_p3 ^ 1'd1);

assign xor_ln46_44_fu_2762_p2 = (tmp_85_fu_2732_p3 ^ 1'd1);

assign xor_ln46_45_fu_2846_p2 = (tmp_87_fu_2816_p3 ^ 1'd1);

assign xor_ln46_46_fu_2930_p2 = (tmp_89_fu_2900_p3 ^ 1'd1);

assign xor_ln46_fu_326_p2 = (tmp_fu_296_p3 ^ 1'd1);

assign ap_return_0 = res_0_0_fu_366_p3;

assign ap_return_1 = res_1_0_fu_450_p3;

assign ap_return_10 = res_10_0_fu_1206_p3;

assign ap_return_11 = res_11_0_fu_1290_p3;

assign ap_return_12 = res_12_0_fu_1374_p3;

assign ap_return_13 = res_13_0_fu_1458_p3;

assign ap_return_14 = res_1445_0_fu_1542_p3;

assign ap_return_15 = res_15_0_fu_1626_p3;

assign ap_return_16 = res_16_0_fu_1710_p3;

assign ap_return_17 = res_17_0_fu_1794_p3;

assign ap_return_18 = res_18_0_fu_1878_p3;

assign ap_return_19 = res_19_0_fu_1962_p3;

assign ap_return_2 = res_2_0_fu_534_p3;

assign ap_return_20 = res_20_0_fu_2046_p3;

assign ap_return_21 = res_21_0_fu_2130_p3;

assign ap_return_22 = res_22_0_fu_2214_p3;

assign ap_return_23 = res_23_0_fu_2298_p3;

assign ap_return_24 = res_24_0_fu_2382_p3;

assign ap_return_25 = res_25_0_fu_2466_p3;

assign ap_return_26 = res_26_0_fu_2550_p3;

assign ap_return_27 = res_2786_0_fu_2634_p3;

assign ap_return_28 = res_28_0_fu_2718_p3;

assign ap_return_29 = res_29_0_fu_2802_p3;

assign ap_return_3 = res_3_0_fu_618_p3;

assign ap_return_30 = res_30_0_fu_2886_p3;

assign ap_return_31 = res_31_0_fu_2970_p3;

assign ap_return_4 = res_4_0_fu_702_p3;

assign ap_return_5 = res_5_0_fu_786_p3;

assign ap_return_6 = res_6_0_fu_870_p3;

assign ap_return_7 = res_7_0_fu_954_p3;

assign ap_return_8 = res_8_0_fu_1038_p3;

assign ap_return_9 = res_9_0_fu_1122_p3;

assign icmp_ln45_16_fu_374_p2 = (($signed(data_1_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_17_fu_458_p2 = (($signed(data_2_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_18_fu_542_p2 = (($signed(data_3_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_19_fu_626_p2 = (($signed(data_4_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_20_fu_710_p2 = (($signed(data_5_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_21_fu_794_p2 = (($signed(data_6_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_22_fu_878_p2 = (($signed(data_7_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_23_fu_962_p2 = (($signed(data_8_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_24_fu_1046_p2 = (($signed(data_9_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_25_fu_1130_p2 = (($signed(data_10_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_26_fu_1214_p2 = (($signed(data_11_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_27_fu_1298_p2 = (($signed(data_12_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_28_fu_1382_p2 = (($signed(data_13_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_29_fu_1466_p2 = (($signed(data_14_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_30_fu_1550_p2 = (($signed(data_15_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_31_fu_1634_p2 = (($signed(data_16_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_32_fu_1718_p2 = (($signed(data_17_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_33_fu_1802_p2 = (($signed(data_18_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_34_fu_1886_p2 = (($signed(data_19_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_35_fu_1970_p2 = (($signed(data_20_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_36_fu_2054_p2 = (($signed(data_21_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_37_fu_2138_p2 = (($signed(data_22_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_38_fu_2222_p2 = (($signed(data_23_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_39_fu_2306_p2 = (($signed(data_24_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_40_fu_2390_p2 = (($signed(data_25_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_41_fu_2474_p2 = (($signed(data_26_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_42_fu_2558_p2 = (($signed(data_27_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_43_fu_2642_p2 = (($signed(data_28_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_44_fu_2726_p2 = (($signed(data_29_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_45_fu_2810_p2 = (($signed(data_30_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_46_fu_2894_p2 = (($signed(data_31_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_290_p2 = (($signed(data_0_val) > $signed(19'd0)) ? 1'b1 : 1'b0);

endmodule //Topo2A_AD_proj_relu_ap_fixed_19_11_5_3_0_ap_ufixed_15_0_4_0_0_relu_config4_s
