// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Topo2A_AD_proj_linear_ap_fixed_12_4_5_3_0_ap_fixed_19_11_5_3_0_linear_config9_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_rst
);


output   ap_ready;
input  [11:0] data_0_val;
input  [11:0] data_1_val;
input  [11:0] data_2_val;
output  [18:0] ap_return_0;
output  [18:0] ap_return_1;
output  [18:0] ap_return_2;
input   ap_rst;

wire  signed [18:0] sext_ln32_fu_36_p1;
wire  signed [18:0] sext_ln32_16_fu_40_p1;
wire  signed [18:0] sext_ln32_17_fu_44_p1;

assign ap_ready = 1'b1;

assign sext_ln32_16_fu_40_p1 = $signed(data_1_val);

assign sext_ln32_17_fu_44_p1 = $signed(data_2_val);

assign sext_ln32_fu_36_p1 = $signed(data_0_val);

assign ap_return_0 = sext_ln32_fu_36_p1;

assign ap_return_1 = sext_ln32_16_fu_40_p1;

assign ap_return_2 = sext_ln32_17_fu_44_p1;

endmodule //Topo2A_AD_proj_linear_ap_fixed_12_4_5_3_0_ap_fixed_19_11_5_3_0_linear_config9_s
