-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Topo2A_AD_proj_linear_ap_fixed_12_4_5_3_0_ap_fixed_19_11_5_3_0_linear_config9_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (11 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (11 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (11 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (18 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (18 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (18 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of Topo2A_AD_proj_linear_ap_fixed_12_4_5_3_0_ap_fixed_19_11_5_3_0_linear_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal sext_ln32_fu_36_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln32_16_fu_40_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln32_17_fu_44_p1 : STD_LOGIC_VECTOR (18 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= sext_ln32_fu_36_p1;
    ap_return_1 <= sext_ln32_16_fu_40_p1;
    ap_return_2 <= sext_ln32_17_fu_44_p1;
        sext_ln32_16_fu_40_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_1_val),19));

        sext_ln32_17_fu_44_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_2_val),19));

        sext_ln32_fu_36_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_0_val),19));

end behav;
